### ISSUE TITLE
Touchbar disappears in 2.307

### ISSUE THREAD

**Issue by kelaun** [fifafu/BetterTouchTool#1553] opened 2017-09-27 08:09 UTC
#### Description of bug/feature request/question:
Sometimes after waking the device from sleep, the touch bar customisations disappear and it goes back to the original macOS version.
I know the alpha was made to fix this issue and I admit it is already better than before, but still not flawless.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch bar

#### Device information:

Type of Mac: MacBook Pro 15 inch with touch bar
macOS version: 10.12.6
BetterTouchTool version: 2.307 (685)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by Krakau** [comment] 2017-09-28 09:24
I also have this problem. Tested with a couple more versions:

Type of Mac: MacBook Pro 15 inch with touch bar
macOS version: 10.12.6
BetterTouchTool version: 2.304 and 2.308 (686)

It was very confusing to understand what was going on since for some reason the only widget that I have visible (Spotify song) was also reverted back to original script:
"return do shell script "date" #example: execute a shell script and use the result"

So even when I was able to get the BTT touchbar visible again it was only showing current date! Do not know if this is a different bug and it only happened once (with version 2.3.04). But the touchbar customization disappearance seems to be a consistent problem.

**Comment by dinpin** [comment] 2017-09-28 10:20
Same here with High Sierra. Started maybe...2 weeks ago?

**Comment by fifafu** [comment] 2017-09-28 22:19
That's weird I can't seem to be able to reproduce this.
Can you find a way to trigger this behavior in 2.308 alpha?

**Comment by dinpin** [comment] 2017-09-29 12:30
still happening on 2.308, i can report it is not necessarily connected to sleep. i happens also without sleep.  happening right now.

i have not figured out what, if anything, is triggering it.

**Comment by andrewheiss** [comment] 2017-09-30 05:03
Same here, in both 2.304 and 2.308 alpha on Sierra. No app-specific custom buttons appear in any applications. No way to turn Touch Bar support back on.

**Comment by fantaaaaaa** [comment] 2017-09-30 16:03
Still the same issue here. mostly after rewake, but also without sleep randomly... im on osx 10.12.6.

**Comment by dennishylau** [comment] 2017-09-30 18:42
I experienced the same issue, and after a bit of experiment, I suspect it has something to do with the app specific settings. I did this and I think it's temporarily fixed:

Under the list of applications > App Specific > Touch Bar Behavior > Change from "Default" to "Show BTT Touch Bar"

**Comment by dinpin** [comment] 2017-10-01 01:03
Touch Bar behaviour settings do not change things for me. Also not rebooting.  Last time I've seen the BTT touch bar has been over 2 days ago

**Comment by fantaaaaaa** [comment] 2017-10-01 07:26
@dennishylau i dont think this should solve the problem permanently as the settings are only app specific. there seems to be a general bug here. @fifafu is there anything we can do to help?

**Comment by fifafu** [comment] 2017-10-01 07:43
So for the people whose Touch Bar doesn't show up at all: it probably got hidden once by user interaction and BTT remembers that state now. You have to tap the BTT icon in the control strip or assign the predefined action "Toggle BetterTouchTool Touch Bar" and trigger it once.

For the people whose Touch Bar just disappears randomly: I have not yet figured out what could cause this. One thing I found was that the Touch Bar did not re-appear after BTT was disabled (e.g. if you disabled BTT for a specific application). This will be fixed with the next version that will be released in a few hours! This may also solve the problem after waking from sleep.

So I hope that will fix most of the issues, I have tested it for quite a while now and couldn't find a situation where the Touch Bar was hidden and did not reappear automatically.

**Comment by fantaaaaaa** [comment] 2017-10-01 08:19
Thanks for the quick response @fifafu.

As feedback from my side: i just have one global BTT bar, i dont show/hide it, its always there (ive even built my own escape key). i am hiding the macOS Bar and havent seen it for months before the update and the recent troubles. i dont have a button to hide it, so i can exclude this as a reason its broken for me. mine disappears after sleep/wake reproducably.

side-question: ive set my touchbar like this: https://www.dropbox.com/s/p6jghmkx9zqkqjp/Screenshot%202017-10-01%2010.16.43.png?dl=0
is there a way to disable the FN key here? i dont need or use the F-buttons and dont want them to appear when i press the N-key.

**Comment by fifafu** [comment] 2017-10-01 09:26
Would be great if you could try v2.310!

**Comment by dinpin** [comment] 2017-10-01 10:10
looking good up until now

**Comment by kelaun** [comment] 2017-10-05 07:19
I still have the issue on 2.310 when I press the function key on the keyboard. I can see the F keys on the bar, but when I leave that mode it returns to the default bar and not the one I configured.

**Comment by ursbraem** [comment] 2017-10-11 10:01
I'm on 2.310 on High Sierra and I don't find a way to make the BTT touchbar appear again. Also, the BTT icon doesn't appear in Control Strip. Is there a way to force launch the btt touchbar from elsewhere?

**Comment by ursbraem** [comment] 2017-10-11 16:18
It magically reappeared

**Comment by Krakau** [comment] 2017-10-12 06:53
I do not know about the rest of you but for me this seems to be solved. After several days I have not seen any strange behaviour.

**Comment by kelaun** [comment] 2017-10-16 14:35
For me it is still there, but less frequently.
Mostly it happens when I click the shortcut to put my Mac to sleep. On wakeup the bar is default, but once I press a modifier key it reverts back to BTT default.

**Comment by fifafu** [comment] 2017-10-16 15:21
@kelaun does switching to an other application also bring the Touch Bar back in your case?

**Comment by kelaun** [comment] 2017-10-16 15:24
@fifafu no this does not seem to help, only the modifier key helps.

**Comment by dinpin** [comment] 2017-10-17 10:36
one this that is now happening is that after sleep/screen lock sometimes the whole btt app closes

**Comment by fifafu** [comment] 2017-10-17 22:51
@dinpin, BTT always closes after sleep, that's intended - however it should automatically restart and re-initialize.

**Closed** 2018-02-03 08:48 UTC
