### ISSUE TITLE
BTT crashes upon opening, cannot get it to stay open

### ISSUE THREAD

**Issue by sorttouchtool** [fifafu/BetterTouchTool#901] opened 2017-05-06 22:08 UTC
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

BTT crashes when I open it, cannot get it to stay open.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Trackpad, entire program

#### Device information:

Type of Mac: Retina 2013 13inch MacBook Pro
macOS version: Latest 10.12.4 Sierra
BetterTouchTool version: 2.11

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I've restarted the system multiple times, but doesn't seem to help.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by osmannuriguler** [comment] 2017-05-07 00:07
Same here! After the last update, it crashes everytime I launch it!

**Comment by osmannuriguler** [comment] 2017-05-07 00:31
I have downloaded this previous version and it works fine.

"btt2.101.zip     2017-05-05 22:53"

But the last update crashes everytime. Hope it gets fixed soon.

**Comment by fifafu** [comment] 2017-05-07 07:06
Weird, according to my logs it seems to work fine on almost all machines that downloaded it.
Thus it's probably something very specific. Can you check if there is a crashlog in the macOS console.app => User Reports?

**Comment by Andru-bonus** [comment] 2017-05-07 08:36
Same here. After last update it works few minutes and than totally hangs. And you can't just relaunch it, because in System Monitor you see the BTT process "do not respond". So you need to kill it first and than - launch again for next few minutes.

**Comment by fifafu** [comment] 2017-05-07 09:02
@Andru-bonus that sounds like a different issue. If that happens please select the app in Activity Monitor, then click on "View => Sample Process". The output of that would be very useful.

**Comment by tkirby** [comment] 2017-05-07 09:49
BTT runs until I use a shortcut then crashes. Since last update of MacOS 10.12.4 on 2015 Macbook Air.

**Comment by fifafu** [comment] 2017-05-07 09:59
@tkirby , please provide a crashlog if possible (Console.app => User Reports)

**Comment by Andru-bonus** [comment] 2017-05-07 11:12
@fifafu Here is process sample you've asked for.
Made the clear reinstall of system couple of weeks ago, also reinstalled BTT clearly after problem - it still persist.
[Sample BetterTouchTool_freeze.txt](https://github.com/fifafu/BetterTouchTool/files/981532/Sample.BetterTouchTool_freeze.txt)

**Comment by fifafu** [comment] 2017-05-07 15:20
@Andru-bonus weird, have you already tried to restart your Mac? From what I can see the freeze is at a location that hasn't changed for months, however it could be caused by some strange trackpad-driver state.

**Comment by cleverjackal** [comment] 2017-05-07 17:50
have you tried turning it off and back on again

**Comment by tkirby** [comment] 2017-05-07 18:34
[Archive.zip](https://github.com/fifafu/BetterTouchTool/files/981839/Archive.zip)

user reports

**Comment by fifafu** [comment] 2017-05-07 18:47
@tkirby these are all for v2.10 :-) Please try upgrading to v2.11, those should be fixed already!

**Comment by Andru-bonus** [comment] 2017-05-07 18:54
@fifafu rebooted, reinstalled with total clearing of system files, restarted...
Before this update it only crushed regularly, now hangs

**Comment by albertcreus** [comment] 2017-05-08 02:42
Same here, any clue how to downgrade while we wait for the fix?

**Comment by dvanoni** [comment] 2017-05-08 04:02
@fifafu This happened to me as well. I've reverted to version 2.10 for the time being.

Below is the crash file from User Reports:
[BetterTouchTool_2017-05-07-135951.crash.txt](https://github.com/fifafu/BetterTouchTool/files/982340/BetterTouchTool_2017-05-07-135951.crash.txt)

**Comment by dvanoni** [comment] 2017-05-08 04:07
@albertcreus Check your Trash for the previous version of BTT—it should be named like `BetterTouchTool (626)`.

If you go to `/Applications` and delete the version of BTT there, you can then move the previous version out of Trash into `/Applications` and rename it to remove the ` (626)` part of the name.

**Comment by KarlPiper** [comment] 2017-05-08 04:11
I'm having this issue as well. Downgrading works for now I guess. If more logs are needed let me know. After downgrading and launching successfully, I killed the relaunch process started by the broken version.

**Comment by zygis** [comment] 2017-05-08 05:40
[crash_report.txt](https://github.com/fifafu/BetterTouchTool/files/982443/crash_report.txt)
Latest version: 2.11
Application launched right after restart. Removed previous version from applications before copying this one.

**Comment by fifafu** [comment] 2017-05-08 05:49
@dvanoni @zygis THANK YOU for the crash reports!! It should now be fixed: https://bettertouchtool.net/releases/btt2.12.zip

The crashreports also explain to me why only a small fraction of users is seeing the issue.

**Comment by albertcreus** [comment] 2017-05-08 05:57
I downgraded to 2.10, working.
My crashes were with 2.12

**Comment by dvanoni** [comment] 2017-05-08 05:59
@fifafu This version has the same issue. I'm curious, what do you think is the cause of the issue?

New crash report attached:
[BetterTouchTool_2017-05-07-225503.crash.txt](https://github.com/fifafu/BetterTouchTool/files/982474/BetterTouchTool_2017-05-07-225503.crash.txt)

**Comment by fifafu** [comment] 2017-05-08 06:02
arg - sorry, I had a typo. Will be fixed in one minute :-) It's related to snap areas.

**Comment by fifafu** [comment] 2017-05-08 06:07
Could you please try once more with this build? https://bettertouchtool.net/releases/btt2.12b.zip

**Comment by dvanoni** [comment] 2017-05-08 06:15
@fifafu It works!

Now I'm just eagerly waiting for my snap areas to show up again 😉 Interestingly, I have a "Trigger Snap Area" action set up as a Touch Bar button, and that still works fine.

Thanks for this fix!

**Comment by zygis** [comment] 2017-05-08 10:26
2.12b works for me. Thanks!

**Comment by KarlPiper** [comment] 2017-05-09 07:32
Many thanks for the quick fix and release.

**Comment by osmannuriguler** [comment] 2017-05-09 08:23
2.12b works like a charm! 
You are the best Andreas. Thanks for the quick fix!

**Comment by wiggitamoo** [comment] 2017-05-11 17:00
I had the same problem using the latest version of BTT on macOS Sierra v10.12.4. The 2.12b fixed my issue too. Thanks for the quick response!

**Closed** 2017-06-04 17:06 UTC
