### ISSUE TITLE
Move window to next monitor doesn't work

### ISSUE THREAD

**Issue by asmeurer** [fifafu/BetterTouchTool#2] opened 2016-12-03 19:07 UTC
I have the following configured as global shortcuts. 

<img width="610" alt="screenshot 2016-12-03 14 06 33" src="https://cloud.githubusercontent.com/assets/71486/20861580/b6856ba0-b961-11e6-8cd7-99c0250b35f3.png">

It doesn't work. I am currently using the Sierra public beta, but it hasn't worked in a very long time. It used to work a very long time ago (I couldn't say exactly when, but it's been a few OS X versions), but it doesn't now.

**Comment by fifafu** [comment] 2016-12-03 19:40
Hi Aaron,

what exactly happens?
I just tried it and it correctly moves the windows from one of my monitors to the next one. However it doesn't change the size, thus depending on resolution differences, the position will be wrong. (I should probably resize it relatively to the screen size, but that's not yet implemented.)

Does the Center on next monitor action work for you?

Best,
Andreas

**Comment by asmeurer** [comment] 2016-12-03 20:44
It does nothing. The center window on next monitor action doesn't work either.

**Comment by fifafu** [comment] 2016-12-03 21:13
Weird, could you describe your screen setup?
How many screens are you using? What are the resolutions? Maybe I can somehow reproduce it.

**Comment by asmeurer** [comment] 2016-12-03 21:19
Here's my displays info

![screenshot 2016-12-03 16 18 18](https://cloud.githubusercontent.com/assets/71486/20862260/2608fe4e-b974-11e6-8ea2-8ca91825d379.png)

I've used different display setups before and none of them have worked. 

I do have the "displays have different spaces" option enabled (although this stopped working long before that option was introduced).

**Comment by asmeurer** [comment] 2016-12-03 21:20
I also tried mapping it to a keyboard shortcut in case there is something wrong with that gesture, but that didn't fix it.

**Comment by fifafu** [comment] 2016-12-03 21:37
Do you remember if this ever worked with the FPD1975 display? Maybe BTT somehow doesn't recognize it correctly.

**Comment by asmeurer** [comment] 2016-12-03 21:40
I think it did, but I can't say with certainty. I have tried this with older computers and other displays, and it hasn't worked.

**Comment by fifafu** [comment] 2016-12-03 22:04
I will try to reproduce it with some other monitors on Monday!

**Comment by ZV95** [comment] 2016-12-04 19:40
On trial of using this on my MacBook with TouchBar, I was unable to reproduce the issue. However, one thing to check briefly is whether or not you may have this setting set up to be app specific rather than global (when I first tested this it only worked in Safari before I noticed that it was only working there as it was set to be app specific). 

Version 1.955 (545) Alpha // 10.12.2 Beta (16C53a)
MacBook Pro (15-inch, Late 2016)
2.6 GHz i7 // 16GB // 256GB // Radeon Pro 450 (2GB)

**Comment by asmeurer** [comment] 2016-12-04 22:01
It is set global.

**Comment by fifafu** [comment] 2016-12-04 22:55
I wonder if it's maybe some other setting you are using that conflicts with this. Could you send me your ~/Library/com.hegenberg.BetterTouchTool.plist (to boastr.net@gmail.com)?

**Comment by fifafu** [comment] 2016-12-05 21:39
Thank you for the plist, I think I may have identified what causes the bug :-)
The checkbox "Use the monitor the mouse is on for all window actions (instead of the monitor the window is on" in Advanced Settings=> Window Moving & Resizing.

I'll look for a fix.

**Comment by asmeurer** [comment] 2016-12-08 21:26
That does seem to fix it, thanks.

**Comment by fifafu** [comment] 2017-03-24 14:14
Closing this because it actually seems to be the intended behavior currently :-). However I'll make this configurable on a per-action basis, so in future versions you'll be able to choose which window to use not only globally but gesture/shortcut/trigger specific.

**Closed by fifafu** 2017-03-24 14:14 UTC
Labels: bug, Need other people who can reproduce the issue

**Comment by staranto** [comment] 2017-07-31 18:05
Hmm... I'm having this problem.  macOS 10.12.6, BTT 2.270.  I have **Rightclick Green Window Button** configured to **Move Window to Next Monitor**.  The Live View utility recognizes that gesture.  However, the window does not move.  It simply maximizes on the current monitor (ie. the default MacOS green button action).

FWIW... I had this exact config working for ages with BetterSnapTool.  I just switched to a Magic Mouse 2 today and this is the only thing I can't get working with BTT.  I did confirm that the action in BST works as expect with the MM2.

Any ideas?

**Comment by dctucker** [comment] 2018-01-23 22:39
It's worth noting that although this behavior may be intended, it is confusing that the checkbox labeled "Use the monitor the mouse is on for all window actions" effectively disables the Move Window to Next Monitor functionality. Maybe if a fix can't be determined, there's a way to notify the user of this by greying out or putting a red X on the affected item.
