### ISSUE TITLE
BTT 2.12 frequently crashing

### ISSUE THREAD

**Issue by blaiseIT** [fifafu/BetterTouchTool#975] opened 2017-05-22 01:57 UTC
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Bug: I often will try a BTT trackpad gesture but nothing will happen. The BTT icon will be in the menu bar but I'll get the spinning beachball if I hover over it. I have to quit the app through activity monitor.
#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Pro Trackpad
#### Device information:

Type of Mac: Retina MacBook Pro
macOS version: 10.12.4
BetterTouchTool version: 2.12 (631)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by ibc** [comment] 2017-05-22 23:52
Same here with 2.11:

* Retina MacBook Pro 13'' (late 2013)
* OS X 10.12.4
* BetterTouchTool version: 2.11 (630)

BetterTouchTool process gets into a "process not responding" state all the time (over 2-4 times a day). It just can be killed with a KILL signal.

**Comment by BonfiresDown** [comment] 2017-05-23 09:23
I have this problem too.

**Comment by sorttouchtool** [comment] 2017-05-24 04:24
This happens to me often after waking the mac. No response, spinning beach ball when hovering over the BTT icon.

**Comment by janrnf** [comment] 2017-05-24 08:56
I have the same problem with version 2.12 (631)

- MacBook Pro 15" Late 2013  
- OS X 10.12.4

It keeps crashing after the Mac was asleep and can only be restarted when the process was ended through the Activity Monitor.

**Comment by fifafu** [comment] 2017-05-25 15:56
Would be great if you could test alpha version 2.14 (get via "Check for Alpha Versions" in the menubar menu item). Unfortunately I still couldn't reproduce the issue here, but I have changed a few things that could be related to the issue.

In general I'm tracking the issue here: #915, thus I'm closing this thread here.

**Closed by fifafu** 2017-05-25 15:56 UTC
