### ISSUE TITLE
Frequent (silent) crashes

### ISSUE THREAD

**Issue by jschram** [fifafu/BetterTouchTool#831] opened 2017-04-22 09:09 UTC
#### Description of bug/feature request/question:
I notice from time to time that my BTT input customisations don't work anymore only to find out the BTT process isn't running anymore. Found in the console that it crashes from time to time. (See linked gist for the crash logs)

It might be related to switching environments though; some crashes seem to occur around moments where I switched between working at home, connected to some peripherals (Dell DP monitor, Logitech Performance MX w/ unified receiver, Magic Trackpad 1) and on the go (just my Mac and a pair of bluetooth headphones sometimes). Maybe disconnecting/connecting the Logitech mouse can be the culprit? Or is BTT not actively polling such USB input devices?

Let me know if I can do something to help you trace down this issue!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
All input customisations stop working, because the BTT process crashes.

#### Device information:

Type of Mac: Macbook Pro Retina 2015 / i7 2.5 GHz / 16GB RAM / 500GB SSD / AMD R9 M370X 2G
macOS version: Sierra 10.12.4
BetterTouchTool version: 2.084 (614)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
I've put two most recent crashes in this gist: https://gist.github.com/jschram/2277ce8b94a45ac5faff1c5257c3fe49

**Comment by ctboeheim** [comment] 2017-04-25 13:05
I came here to report very similar symptoms. It seems to be triggered by joining up with the apple trackpad when I return to the office.  At all other locations where the trackpad isn't present the crash doesn't occur. I can upload crash dumps as well, but they look very similar to the ones that were already uploaded.

**Comment by fifafu** [comment] 2017-04-25 14:18
@ctboeheim that's interesting! If possible still submit one of the crashlogs, the more I can get the higher the chance one of them helps me identify the issue.

**Comment by ctboeheim** [comment] 2017-04-25 14:28
Ok, here is the latest crash log:

https://gist.github.com/ctboeheim/7543ed0ae6124569266f20bfeaf72941
Thanks for looking at it!

**Comment by drteethandtheelectricmayhem** [comment] 2017-04-26 18:21
I have a similar problem. Random crashes with 2.071 on macOS 10.12.4. The time of the crash relates to starting my mac this morning at a different location (I don't know if this is relevant). My previous location had a trackpad and keyboard connected with bluetooth. My crash location didn't have either connected.

From console:

Apr 26 10:02:09 Noels-MacBook-Pro com.apple.xpc.launchd[1] (com.hegenberg.BTTRelaunch.82912[15753]): Service exited due to signal: Terminated: 15 sent by BetterTouchTool[18546]

**Comment by jdmorgenstein** [comment] 2017-04-27 16:10
Same issue here with 2.071 on 10.12.4. This typically happens after the computer for a while.

**Comment by amonshiz** [comment] 2017-04-28 13:26
Ditto on this. :(

**Comment by fifafu** [comment] 2017-05-01 16:20
I'm now relatively sure that this crash is somehow caused by rendering the Menubar icon. I don't have a real solution yet, but you could hide the BTT menubar icon for now 

![image](https://cloud.githubusercontent.com/assets/8820811/25585432/cf39dd12-2e9a-11e7-9210-adad830eeac0.png)

**Comment by amonshiz** [comment] 2017-05-01 17:32
That is unfortunate because i like to keep my dock really empty. I also have the dark theme turned on for my mac if that makes a difference.

**Comment by fifafu** [comment] 2017-05-01 17:37
@amonshiz your crash seems to be the only unrelated one here :-) It seems in your case the system was unable to start another process, maybe it was out of resources or similar. Do you have any other crashlogs?

**Comment by vinzenz** [comment] 2017-05-10 06:38
https://gist.github.com/vinzenz/71eb2d8bea5f86cefdbde15217a15c8c Same here

**Comment by amonshiz** [comment] 2017-05-11 14:03
@vinzenz interesting, i will watch out for that too because i tend to connect and disconnect from an external monitor multiple times a day.

**Comment by vinzenz** [comment] 2017-05-11 16:21
In my case it changes also the scale I run the highest resolution when I have no external screens and scale when having external screens since those aren't retina

**Comment by jschram** [comment] 2017-05-11 20:31
Yes connecting or disconnecting an external screen could be related. No issues with resolutions though, as my external monitor is 4k that's configured to use HiDPI as well. On the other hand; my Macbook (15" retina) runs at 1920x1200, so not exactly retina as it's supposed to be.

**Comment by drteethandtheelectricmayhem** [comment] 2017-05-11 20:40
An update.

After disabling the Menubar Icon, BTT is way more stable. I think I’ve only had one crash in over a week where before it was almost daily. (Thank you.)

On my MBP, I use different displays including target display mode on an iMac. It is possible the problem usually occurred from TDM on my iMac at home to no display at work. At work I often start without a display but during the day use various displays.


-Noel

**Comment by fifafu** [comment] 2017-05-11 20:52
Thanks for the Update! I'll try to figure out what exactly is causing this.

**Comment by drteethandtheelectricmayhem** [comment] 2017-05-16 18:07
One crash this morning and I noticed this is the only BTT* process.



Maybe it is stuck relaunching?

**Comment by mankerbrandt** [comment] 2017-05-18 13:12
Same problem here, frequent crashes when waking from sleep.  The only peripheral I've been using is an external monitor.  After reading this thread, I just removed BTT from the menu bar, I'll report back if the crashes continue.  Version info and debug logs below:

-BTT Version 2.12
-Mac OS X 10.12.4
-MacBook Pro (Retina, 13-inch, Early 2015)

[BetterTouchToolDebug.zip](https://github.com/fifafu/BetterTouchTool/files/1010964/BetterTouchToolDebug.zip)

**Comment by haynar** [comment] 2017-06-02 07:53
@fifafu looks like hiding menubar icon lowers the chance of crash, but doesn't remove it. It still crashes on wakeup but not every time like it was with the icon shown. I hope this will somehow help.

**Comment by cmsj** [comment] 2017-06-09 15:17
fwiw we have a very similar looking crash happening in Hammerspoon (http://crashes.to/s/4f66b4a188b), but so far no users have come forward with a bug report, so I know nothing about how to reproduce it :/

**Comment by cmsj** [comment] 2017-06-09 15:34
(I also filed a Radar about this, mirrored at https://www.openradar.appspot.com/32675107 , because I'm not at all convinced that we are doing something wrong here, and the stack trace is so long that the OS really ought to be catching this, imo)

**Comment by cmsj** [comment] 2017-10-13 06:44
FYI, the radar I filed was closed as a duplicate:

“Engineering has determined that your bug report (32675107) is a duplicate of 19759543 and will be closed. ”

**Comment by fifafu** [comment] 2017-10-13 06:56
@cmsj, mine too! However I haven't noticed the issue on High Sierra yet, have you?

**Comment by drteethandtheelectricmayhem** [comment] 2017-10-13 14:54
I just noticed BTT was crashing when BTT starts in High Sierra. I believe it was never starting. I grabbed the system log message but I forgot to get the BTT version # prior to reinstalling. 

Oct 13 07:47:20 Noels-iMac BetterTouchTool[51902]: BetterTouchTool(51902,0x7fff9a55d340) malloc: *** error for object 0x6080000c4360: Invalid pointer dequeued from free list
	*** set a breakpoint in malloc_error_break to debug
Oct 13 07:47:20 Noels-iMac com.apple.xpc.launchd[1] (com.hegenberg.BetterTouchTool.8188[51902]): Service exited with abnormal code: 1

Upon downloading the latest version, it runs without crashing at BTT start. I’ll see how stable it is with the Menubar icon enabled.


-Noel

**Comment by cmsj** [comment] 2017-10-16 06:51
@fifafu is tentatively say that our crash reports for this have reduced since 10.13 was released :)

**Comment by jschram** [comment] 2017-10-16 07:05
For me, it's been stable for the last few months. Running latest version, still on Mac OS Sierra.

**Closed** 2017-11-19 19:15 UTC

**Comment by j5shi** [comment] 2018-07-23 10:01
BTT keep crashing constantly every once in a while when I put my MBP Early 2015 (macOS High Sierra 10.13.6) into sleep (using sleep from menu and also keep lid closed). The crash also causes battery drain at ~8% / 4h.

```
Jul 23 14:49:02 Jias-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000006b.BetterTouchTool[1989]): Service exited due to signal: Terminated: 15 sent by BTTRelaunch[1994]
Jul 23 14:49:02 Jias-MacBook-Pro systemstats[50]: assertion failed: 17G65: systemstats + 914800 [D1E75C38-62CE-3D77-9ED3-5F6D38EF0676]: 0x40
Jul 23 14:49:02 Jias-MacBook-Pro com.apple.xpc.launchd[1] (com.hegenberg.BTTRelaunch.7696[1994]): Service exited due to signal: Terminated: 15 sent by BetterTouchTool[2138]
Jul 23 14:49:02 Jias-MacBook-Pro systemstats[50]: assertion failed: 17G65: systemstats + 914800 [D1E75C38-62CE-3D77-9ED3-5F6D38EF0676]: 0x40
Jul 23 14:49:03 Jias-MacBook-Pro BetterTouchTool[2138]: assertion failed: 17G65: libxpc.dylib + 75013 [0BC7AD67-671D-31D4-8B88-C317B8379598]: 0x89
Jul 23 14:49:22 Jias-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.quicklook[2147]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.quicklook
Jul 23 15:12:22 Jias-MacBook-Pro syslogd[38]: ASL Sender Statistics
Jul 23 15:12:23 Jias-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000006c.BetterTouchTool[2138]): Service exited due to signal: Terminated: 15 sent by BTTRelaunch[2143]
Jul 23 15:12:23 Jias-MacBook-Pro systemstats[50]: assertion failed: 17G65: systemstats + 914800 [D1E75C38-62CE-3D77-9ED3-5F6D38EF0676]: 0x40
Jul 23 15:12:23 Jias-MacBook-Pro com.apple.xpc.launchd[1] (com.hegenberg.BTTRelaunch.7696[2143]): Service exited due to signal: Terminated: 15 sent by BetterTouchTool[2151]
Jul 23 15:12:23 Jias-MacBook-Pro systemstats[50]: assertion failed: 17G65: systemstats + 914800 [D1E75C38-62CE-3D77-9ED3-5F6D38EF0676]: 0x40
Jul 23 15:12:24 Jias-MacBook-Pro BetterTouchTool[2151]: assertion failed: 17G65: libxpc.dylib + 75013 [0BC7AD67-671D-31D4-8B88-C317B8379598]: 0x89
Jul 23 15:12:28 Jias-MacBook-Pro xpcproxy[2157]: libcoreservices: _dirhelper_userdir: 529: bootstrap_look_up returned (ipc/send) invalid destination port
Jul 23 15:12:28 Jias-MacBook-Pro netbiosd[2157]: DEPRECATED USE in libdispatch client: Setting timer interval to 0 requests a 1ns timer, did you mean FOREVER (a one-shot timer)?
Jul 23 15:12:44 Jias-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.quicklook[2161]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.quicklook
Jul 23 16:12:29 Jias-MacBook-Pro syslogd[38]: ASL Sender Statistics
Jul 23 16:12:30 Jias-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000006d.BetterTouchTool[2151]): Service exited due to signal: Terminated: 15 sent by BTTRelaunch[2156]
Jul 23 16:12:30 Jias-MacBook-Pro systemstats[50]: assertion failed: 17G65: systemstats + 914800 [D1E75C38-62CE-3D77-9ED3-5F6D38EF0676]: 0x40
Jul 23 16:12:30 Jias-MacBook-Pro com.apple.xpc.launchd[1] (com.hegenberg.BTTRelaunch.7696[2156]): Service exited due to signal: Terminated: 15 sent by BetterTouchTool[2167]
Jul 23 16:12:30 Jias-MacBook-Pro systemstats[50]: assertion failed: 17G65: systemstats + 914800 [D1E75C38-62CE-3D77-9ED3-5F6D38EF0676]: 0x40
Jul 23 16:12:31 Jias-MacBook-Pro BetterTouchTool[2167]: assertion failed: 17G65: libxpc.dylib + 75013 [0BC7AD67-671D-31D4-8B88-C317B8379598]: 0x89
Jul 23 16:12:35 Jias-MacBook-Pro xpcproxy[2174]: libcoreservices: _dirhelper_userdir: 529: bootstrap_look_up returned (ipc/send) invalid destination port
Jul 23 16:12:35 Jias-MacBook-Pro netbiosd[2174]: DEPRECATED USE in libdispatch client: Setting timer interval to 0 requests a 1ns timer, did you mean FOREVER (a one-shot timer)?
Jul 23 16:12:51 Jias-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.quicklook[2178]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.quicklook
Jul 23 16:49:27 Jias-MacBook-Pro syslogd[38]: ASL Sender Statistics
Jul 23 16:49:28 Jias-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000006e.BetterTouchTool[2167]): Service exited due to signal: Terminated: 15 sent by BTTRelaunch[2172]
Jul 23 16:49:28 Jias-MacBook-Pro systemstats[50]: assertion failed: 17G65: systemstats + 914800 [D1E75C38-62CE-3D77-9ED3-5F6D38EF0676]: 0x40
Jul 23 16:49:28 Jias-MacBook-Pro com.apple.xpc.launchd[1] (com.hegenberg.BTTRelaunch.7696[2172]): Service exited due to signal: Terminated: 15 sent by BetterTouchTool[2181]
Jul 23 16:49:28 Jias-MacBook-Pro systemstats[50]: assertion failed: 17G65: systemstats + 914800 [D1E75C38-62CE-3D77-9ED3-5F6D38EF0676]: 0x40
Jul 23 16:49:29 Jias-MacBook-Pro BetterTouchTool[2181]: assertion failed: 17G65: libxpc.dylib + 75013 [0BC7AD67-671D-31D4-8B88-C317B8379598]: 0x89
Jul 23 16:49:48 Jias-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.quicklook[2189]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.quicklook
Jul 23 17:12:48 Jias-MacBook-Pro syslogd[38]: ASL Sender Statistics
Jul 23 17:12:48 Jias-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000006f.BetterTouchTool[2181]): Service exited due to signal: Terminated: 15 sent by BTTRelaunch[2185]
Jul 23 17:12:49 Jias-MacBook-Pro com.apple.xpc.launchd[1] (com.hegenberg.BTTRelaunch.7696[2185]): Service exited due to signal: Terminated: 15 sent by BetterTouchTool[2190]
Jul 23 17:12:50 Jias-MacBook-Pro systemstats[50]: assertion failed: 17G65: systemstats + 914800 [D1E75C38-62CE-3D77-9ED3-5F6D38EF0676]: 0x40
Jul 23 17:12:51 --- last message repeated 2 times ---
Jul 23 17:12:51 Jias-MacBook-Pro BetterTouchTool[2190]: assertion failed: 17G65: libxpc.dylib + 75013 [0BC7AD67-671D-31D4-8B88-C317B8379598]: 0x89
Jul 23 17:12:51 Jias-MacBook-Pro systemstats[50]: assertion failed: 17G65: systemstats + 684622 [D1E75C38-62CE-3D77-9ED3-5F6D38EF0676]: 0x7fdd6b610a30
Jul 23 17:12:54 Jias-MacBook-Pro xpcproxy[2199]: libcoreservices: _dirhelper_userdir: 529: bootstrap_look_up returned (ipc/send) invalid destination port
Jul 23 17:12:54 Jias-MacBook-Pro netbiosd[2199]: DEPRECATED USE in libdispatch client: Setting timer interval to 0 requests a 1ns timer, did you mean FOREVER (a one-shot timer)?
Jul 23 17:13:11 Jias-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.quicklook[2203]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.quicklook
Jul 23 17:40:13 Jias-MacBook-Pro syslogd[38]: ASL Sender Statistics
Jul 23 17:40:13 Jias-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000070.BetterTouchTool[2190]): Service exited due to signal: Terminated: 15 sent by BTTRelaunch[2194]
Jul 23 17:40:13 Jias-MacBook-Pro systemstats[50]: assertion failed: 17G65: systemstats + 914800 [D1E75C38-62CE-3D77-9ED3-5F6D38EF0676]: 0x40
Jul 23 17:40:15 Jias-MacBook-Pro com.apple.xpc.launchd[1] (com.hegenberg.BTTRelaunch.7696[2194]): Service exited due to signal: Terminated: 15 sent by BetterTouchTool[2206]
Jul 23 17:40:15 Jias-MacBook-Pro systemstats[50]: assertion failed: 17G65: systemstats + 914800 [D1E75C38-62CE-3D77-9ED3-5F6D38EF0676]: 0x40
Jul 23 17:40:16 --- last message repeated 1 time ---
Jul 23 17:40:16 Jias-MacBook-Pro BetterTouchTool[2206]: assertion failed: 17G65: libxpc.dylib + 75013 [0BC7AD67-671D-31D4-8B88-C317B8379598]: 0x89
Jul 23 17:40:16 Jias-MacBook-Pro systemstats[50]: assertion failed: 17G65: systemstats + 684622 [D1E75C38-62CE-3D77-9ED3-5F6D38EF0676]: 0x7fdd6b610a30
Jul 23 17:40:19 Jias-MacBook-Pro systemstats[50]: assertion failed: 17G65: systemstats + 914800 [D1E75C38-62CE-3D77-9ED3-5F6D38EF0676]: 0x40
Jul 23 17:40:19 Jias-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Jul 23 17:40:36 --- last message repeated 1 time ---
Jul 23 17:40:36 Jias-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.quicklook[2226]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.quicklook
```
