### ISSUE TITLE
Multiple Date/Time Widgets with Timezone Support 

### ISSUE THREAD

**Issue by spieglio** [fifafu/BetterTouchTool#2059] opened 2018-02-04 13:03 UTC
I'd love to see support for multiple Date/Time Widgets with Timezone support so that I could have my clients time zone and my own in the touch bar at all times.

Thanks for this amazing tool. It's impressive how useful the touch bar becomes with BTT!

**Comment by hholcombe** [comment] 2018-03-14 02:27
Dupe of https://github.com/fifafu/BetterTouchTool/issues/648

**Closed** 2018-03-14 05:01 UTC
