### ISSUE TITLE
using with Intellij IDE have some bug

### ISSUE THREAD

**Issue by cyhhao** [fifafu/BetterTouchTool#1371] opened 2017-08-24 09:28 UTC
#### Description of bug/feature request/question:
When using Intellij IDE like Pycharm, IDEA , if you click between the two lines quickly, it will select the code between them. As if I was dragging.
 ("Click" is press lightly the trackpad, not "tap" or "press heavily")

I'm not set any Gesture , and if I close BTT it will be recover.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Trackpad

#### Device information:

Type of Mac: MacBook Pro Mid 2015
macOS version: 10.12.6
BetterTouchTool version:  2.293

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
![image](https://user-images.githubusercontent.com/5381613/29659233-28cddbc6-88f0-11e7-9e01-d0344b0a11f5.png)

**Comment by 54vanya** [comment] 2017-08-25 05:01
MacBook Pro Mid 2016, have this too

**Comment by bartrail** [comment] 2017-08-25 12:55
Macbook Pro Late 2016 TB, can confirm too

**Comment by fifafu** [comment] 2017-08-25 14:58
I can reproduce this, however it seems to be a bug in IntelliJ. 
(It happens as soon as I activate an listen only even tap like this: ```CGEventTapCreate(
                                    kCGHIDEventTap, kCGTailAppendEventTap,
                                    kCGEventTapOptionListenOnly
                                    , eventMaskMouseDragged, callbackFUnction, nil);```

In previous versions I used a modifying event  tap, however I removed that for performance reasons. In theory listen only taps are completely harmless, thus I really wonder what jetbrains is doing there.

For now I'll probably add a workaround to use an intercepting eventap while IntelliJ based products are in use. Until I have added this you can either disable BTT for IntelliJ or downgrade via https://boastr.net/releases

**Comment by nahu** [comment] 2017-08-25 19:07
Macbook Pro 15 Mid 2017 TB, confirmed in both IntelliJ Idea 2017.1 and IntelliJ Idea 2017.2

**Comment by borisspektor** [comment] 2017-08-26 22:58
Happens to me too, plus it also happens in Terminal. Macbook pro 2017 in Android Studio 2.3.3.

**Comment by fifafu** [comment] 2017-08-27 21:11
could you check whether this is fixed in v2.294 alpha? (get via "Check for alpha version updates" or here: https://bettertouchtool.net/releases/btt2.294.zip )

**Comment by borisspektor** [comment] 2017-08-28 07:22
Seems like the issue is fixed in this version. Thanks!

**Comment by cyhhao** [comment] 2017-08-28 07:35
Fixed in v2.294, Thank you !!

**Closed** 2017-08-29 06:21 UTC

**Comment by PinStudios** [comment] 2017-08-29 19:52
Omg this is salvation. Also while trying to overcome this I have noticed that disabling BTT is broken (both active app & all apps) - it works when you do it, but when you focus something else and return to intellij it reverts to broken behavior.

**Comment by bbredewold** [comment] 2017-08-30 07:32
What a relieve! Thanks for quickly fixing this bug! It drove me crazy!
