### ISSUE TITLE
'BetterTouchTool (Autoupdate) wants to make changes' prompt for user name and password

### ISSUE THREAD

**Issue by jimmyodonnell** [fifafu/BetterTouchTool#2015] opened 2018-01-24 00:18 UTC
#### Description of bug/feature request/question:
BTT prompts me to update, and I choose 'Install Update'. Download is successful, I click to allow it to install and relaunch, and then get a prompt from 'BetterTouchTool (Autoupdate)' for my user name and password. I do not have admin/SU privileges. I use a chip card/reader + pin to log in; no combination of password/PIN allows me to finish the update.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Not applicable.

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2015)
macOS version: 10.12.6 (16G1114)
BetterTouchTool version: 2.318 (702)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
None available.

**Comment by jimmyodonnell** [comment] 2018-01-24 00:20
A similar issue can be found on the ImageOptim project: https://github.com/ImageOptim/ImageOptim/issues/190

**Comment by fifafu** [comment] 2018-01-24 07:23
I think BTT is already configured correctly. This can however also happen if you just don't have the write permissions for the BetterTouchTool app folder for some reason.

You could try to download a fresh copy from my website https://boastr.net/downloads and see if you can manually copy it to your apps folder.

**Comment by jimmyodonnell** [comment] 2018-01-24 18:05
I see. I don't have write privileges to `/Applications/`, but I do have write privileges in `~/Applications/`. I moved BTT there and was able to update successfully. I am able to update other software in `/Applications/` without needing admin authentication (e.g. I just updated Firefox). As the sole user of this machine and BTT, is there any reason I should not keep BTT in `~/Applications/`? If not, it might be useful to advise others in this situation to install to the user Applications directory.

Thanks for the quick response!

**Comment by fifafu** [comment] 2018-01-24 18:29
It's definitely fine to have it in ~/Applications/

I'll try to figure out the reason why you can update other software in the /Applications folder, maybe for some reason the file permissions of BTT are wrong.

**Comment by fifafu** [comment] 2018-02-02 16:13
I'm closing here for now, because I haven't had any other similar reports and couldn't reproduce the issue on my machines. Maybe something was weird with the permissions.

In case you still run into problems please let me know . I think your ~/Applications workaround should work fine :-)

**Closed by fifafu** 2018-02-02 16:13 UTC
