### ISSUE TITLE
Left clicks w/ Magic Mouse 2 not always registering in Chrome 61

### ISSUE THREAD

**Issue by edemicco** [fifafu/BetterTouchTool#1445] opened 2017-09-06 17:21 UTC
#### Description of bug/feature request/question:

Since Chrome 61.0.3163.79 (released 6/5/17), left clicks on links are often not registered if the mouse (Magic Mouse 2) is moving while clicking. Clicks are only registered reliably if you stop moving the mouse before clicking. The problem does not occur in other browsers. It did not occur in the previous version of Chrome. It does occur in the latest Chrome Canary (63.0.3207.0). Which actions are configured in BTT does not seem to matter - merely having it running causes the issue. It persists after resetting all BTT settings.

Steps taken without resolving:

- restarting BTT/the machine
- resetting all BTT settings
- downgrading from BTT v2.297 to v2.291

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Mouse 2
(Magic Trackpad and Apple BT keyboard also present, but clicking in Chrome on the trackpad seems okay.)

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2015)
macOS version: 10.12.6 (16G29)
BetterTouchTool version: 2.297

**Comment by fifafu** [comment] 2017-09-06 19:46
Weird I can't think of anything that's special to the Magic Mouse 2 in combination with Chrome.

I'll keep an eye on this. Does disabling BTT for Chrome help? Does quitting BTT get rid of the issue?

**Comment by edemicco** [comment] 2017-09-06 19:53
To answer your questions:

Yes, disabling BTT for Chrome gets rid of the issue.
Yes, quitting BTT gets rid of the issue.

**Comment by fifafu** [comment] 2017-09-06 20:03
I think I'm able to reproduce the issue. I'll need to look deeper into it this weekend, currently I'm not sure whether I'll be able to add a real fix, but maybe a workaround. I think Chrome may have added some very delicate timing logic that decides when a click is a click and when a drag (usually apps get that information from the system). Maybe the few milliseconds BTT needs to process the events disturb this, for other apps the system automatically cares for this.

However this will hit various other apps, not only BTT. I'll report the issue to Google.

**Comment by edemicco** [comment] 2017-09-06 20:09
Thank you for looking into it! When I have time I will try some other mice and see if the problem occurs with them.

**Comment by dndrsn** [comment] 2017-09-06 21:09
I have the same issue.  I noticed it in the Chrome 61 beta.  Went back to the Chrome 60 stable, but now that Chrome updated to 61 today, it came back again.

**Comment by alopecoid** [comment] 2017-09-09 14:47
I am experiencing the same issue, using Magic Mouse 1:

BetterTouchTool 2.297
Google Chrome 61.0.3163.79 (Official Build) (64-bit)
macOS Sierra 10.12.6

**Comment by dndrsn** [comment] 2017-09-09 14:56
If the issue is not fixable, perhaps an option to disable just the functionality that causes the issue on a per app basis?  Right now I have to disable BTT completely for Chrome.  Would be great to keep other functions that don't cause this issue enabled for Chrome.

**Comment by fifafu** [comment] 2017-09-09 15:06
Unfortunately I have a hard time figuring out what causes this at all, because it seems like on High Sierra beta this is the standard way how Chrome behaves (there doesn't seem to be a difference between running BTT and not running BTT).

I think this is a bug in Chrome that happens to appear while BTT is running. I'll check again on my Sierra machine later!

**Comment by fifafu** [comment] 2017-09-09 15:31
Someone here created a nice test-site that allows me to more easily reproduce the issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=763642&q=click&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

If possible please star this issue by clicking the little star icon on the top left of the Chrome bugtracker

**Comment by taenzerme** [comment] 2017-09-15 10:11
I can confirm this with Magic Mouse 2 on Sierra and Chrome 61.0.3163.91. Unfortunately, disabling BetterTouchTool/BetterSnapTool doesn't make a difference. It's quite annoying actually. Is there anything one can do to help by submitting this somewhere else or providing report info?

**Comment by fifafu** [comment] 2017-09-15 10:16
Nope, the chromium team is already looking into it.
Yoi can star /  comment on the issue mentioned above.

**Comment by thisisablock** [comment] 2017-09-20 10:30
its definitely related to btt. tested that behavior on macbook and imac with magic mouse 1 + 2. Current Canary not fixes that issue. the only possibility to circumvent that bug is to close btt :(

**Comment by fifafu** [comment] 2017-09-20 10:42
@thisisablock, yes the Chrome team is already looking into it. It's a bug with CGEventTaps in combination with Chrome. Unfortunately there is nothing I can do about this in BTT.

**Comment by fifafu** [comment] 2017-09-25 20:19
Please try the current BetterTouchTool alpha (2.307). I have added a temporary workaround as discussed with the Chromium team.  (Get via "check for alpha version updates")

**Comment by isnotnull** [comment] 2017-09-25 20:59
With BTT alpha (2.307), left clicks are back to normal in Chrome 61, but seems still not in Chrome Canary 63.

**Comment by fifafu** [comment] 2017-09-25 21:03
Ah sorry that's because the workaround currently only looks for the stable version bundleidentifier. I'll add a check for the canary version tomorrow.

**Comment by aholtzmbw** [comment] 2017-09-26 11:24
I'd say so far so good with the latest Chrome and the alpha BTT.

**Comment by Brendonwbrown** [comment] 2017-09-28 16:43
Thank you. Having this issue. Will test the beta and report back.

**Comment by ben174** [comment] 2017-10-04 00:16
I am still experiencing this issue with the latest BetterTouchTool (2.3.10) when switching from Terminal to a Chrome window. It's as if a mouse drag has occurred, because half of the text in my Terminal window will suddenly become highlighted. It happens so often I've actually had to resort to quitting BetterTouchTool when working heavily in Terminal.app :(

**Comment by lamberttraccard** [comment] 2017-10-12 07:17
Hi, I don't use BetterTouchTool and I'm experiencing the same issue. I thought my magic mouse was broken but then noticed it's only happening with chrome.

**Comment by lamberttraccard** [comment] 2017-10-12 07:22
After reading an other thread, this is happening with Magnet as well.

**Comment by VAL-3000** [comment] 2017-10-13 17:55
Having the same problem as well. It only seems to happen in Chrome when trying to click on a checkbox associated with an individual email: a single click does not register as a check, though it does highlight / activate a blue outline around the empty checkbox). 

It appears to only happen with my Magic Mouse (trackpad works fine). All systems are up to date.

**Comment by fifafu** [comment] 2017-10-13 17:58
@VAL-3000 the Chrome issue is fixed in BTT 2.310, if you still encounter it you need to check for other apps that also use CGEventTaps. The dragging issue some other users described here is something different/unrelated.

**Comment by VAL-3000** [comment] 2017-10-13 18:01
Thanks @fifafu. I neglected to mention that I do not use BTT. Not sure what other apps use CGEventTaps but I'll ask google, lol.

**Comment by fifafu** [comment] 2017-10-13 18:03
Think of any app that reacts to mouse clicks or movements without being the frontmost app.

**Comment by fifafu** [comment] 2017-10-16 08:53
Closing here, I'm continue to track the dragging issue here: #1580

**Closed by fifafu** 2017-10-16 08:53 UTC
Labels: not-fixable

**Comment by RubiousShaun** [comment] 2017-11-06 12:03
We are having this problem too, I have Magnet installed but some of my colleagues don't. None of us have BTT.

**Comment by Vogod** [comment] 2017-11-08 07:56
The same problem from... I INSTALLED MAGNET!! It seems it is the problem. I had High Sierra and Chrome 60 and 61 and no problems. Perhaps there is another app interfering...

**Comment by jkmajcen** [comment] 2017-11-14 17:26
Killing Magnet cleared up the problem on my end. Go figure.
