### ISSUE TITLE
Preset switch problem 849 unchanged with 2.095

### ISSUE THREAD

**Issue by CappyD** [fifafu/BetterTouchTool#863] opened 2017-05-01 23:14 UTC
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
In 2.095, issue 849 seems unchanged. Should it be fixed there? A TB button defined with action Switch to Preset, and in the resulting dialog, Master is set to a preset and only it is checked in the "additional" section below. When the TB button is pressed, the TB goes blank.  It does not show the buttons defined in the assigned preset.  Shouldn't it work this way?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
touch bar

#### Device information:

Type of Mac: 2016 MBPro 13"
macOS version: 10.12.4
BetterTouchTool version: 2.095

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment] 2017-05-02 05:02
I'm not sure, maybe I misunderstand something. 
See the attached screenshots:

Configuration in Preset "Default"
![image](https://cloud.githubusercontent.com/assets/8820811/25604624/2d3bd842-2f05-11e7-9ef9-e48d53f0e0e9.png)
![image](https://cloud.githubusercontent.com/assets/8820811/25604634/3c113c7c-2f05-11e7-862e-69cd18814fc9.png)


Configuration in Preset "Test"
![image](https://cloud.githubusercontent.com/assets/8820811/25604605/f4c56460-2f04-11e7-9186-3cb7fe005a07.png)
![image](https://cloud.githubusercontent.com/assets/8820811/25604609/04065ff6-2f05-11e7-8e72-4ebf6203f4fe.png)


This allows me to successfully switch between the two presets, both showing the button to switch to the other preset.

**Comment by CappyD** [comment] 2017-05-03 03:27
Thanks for preparing those screen shots Andreas.  Yes, that is the way I had it set up.  After more investigation I found that when I pressed the "switch to test" button (as you've called it), then open BBT prefs, I do not see the full list of apps on the left as in the Default preset - only Global and Finder appear. But I had defined some TB buttons for an app in the Test preset and that app does not appear in the list. This would seem to explain why the TB is blanked out when that app is active, though it's still a little odd because a global button should still appear. Note that the buttons defined under Global (like your "switch to default") do appear when another app or Finder is active. I have to manually switch back to the Default preset in the BBT prefs, close the prefs and reopen it to see the full list of apps.

**Comment by fifafu** [comment] 2017-05-03 04:30
It's possible that some things got confused due to the display bug in the previous version (it may have shown the app in the list although it shouldn't have). 
Maybe try to create another preset and see if it works correctly there.

**Comment by fifafu** [comment] 2017-05-03 06:57
I made one more possibly related change in 2.096, would be great if you could test it.

**Comment by CappyD** [comment] 2017-05-03 13:22
Thanks.  It seems to be behaving consistently now with how you have designed BTT.  Which means that any Global buttons in the preset only show up when an app that has been added to the preset is active.  Any other app shows it's default, non-BTT TB.  One must add all apps to the preset in order to have the global buttons visible.

**Comment by fifafu** [comment] 2017-05-03 16:00
@CappyD it shouldn't be like that. Global buttons should always appear if they are defined in the global section. I'll check if I can reproduce the issue here.

**Comment by fifafu** [comment] 2017-05-03 16:35
Mhh it seems to work correctly here.

Both global buttons defined show up correctly, this doesn't work for you?

![image](https://cloud.githubusercontent.com/assets/8820811/25671131/387dbf74-302f-11e7-9652-b13dd4bd4df2.png)
![image](https://cloud.githubusercontent.com/assets/8820811/25671149/417efc28-302f-11e7-8901-626841b37ba8.png)

**Comment by CappyD** [comment] 2017-05-03 23:31
My Test preset looks like this:

![test1](https://cloud.githubusercontent.com/assets/24412403/25685499/f8ead89a-3035-11e7-943b-fb29adebdc06.jpeg)

![test2](https://cloud.githubusercontent.com/assets/24412403/25685526/1ee96fca-3036-11e7-8715-f0edc2707c9d.jpeg)

Now, if you go to the Messages app and press the Test TB button to switch to the Test preset, I see both the "msgs back" and the "global back" buttons in the TB.  If I then go to any other app - for instance, the Mail or Calendar app - you see only the MacOS default TB for those apps.  BTW, for the Messages app in the Test preset, I have set "app specific: TB behavior: show BTT TB, hide control strip".

**Comment by fifafu** [comment] 2017-05-04 10:47
Very weird. Could you try updating to v 2.099 alpha, then opening the BTT preferences -> About and click the new "export debug information" button?

It will create a folder "BetterTouchToolDebug" on your Desktop. Would be great if you could send me the contents of that folder

**Comment by CappyD** [comment] 2017-05-04 12:59
Sure... I sent it to gmail address.

**Comment by CappyD** [comment] 2017-05-04 13:06
I should mention that I had removed the global button to "switch to test" preset, but the Test preset is there as I last described it.  if you need the debug info resent, let me know.

**Comment by fifafu** [comment] 2018-02-03 08:57
I'm currently closing some older issues, in case this still doesn't work correctly, please comment again or open a new issue.

I'll have much more time moving forward as I'm now self-employed. Please excuse not being able to solve/reply to this earlier.

**Closed by fifafu** 2018-02-03 08:57 UTC
