### ISSUE TITLE
4 Finger Tap activated after performing Pinch/Spread with thumb and 3 fingers

### ISSUE THREAD

**Issue by mcarreira** [fifafu/BetterTouchTool#908] opened 2017-05-07 19:10 UTC
#### Description of bug/feature request/question:

If you have an action for gesture "4 Finger Tap" it will get activated after you perform the "Pinch with thumb and 3 fingers" or "Spread with thumb and 3 fingers".

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Trackpad.

#### Device information:

Type of Mac: MacBook pro late 2013
macOS version: OSX Sierra 10.12.4 (16E195)
BetterTouchTool version: 2.11 (630)

If you have any problem when trying to reproduce this error, just let me know. I can provide more information in case you need it. Thanks.

**Comment by fifafu** [comment] 2017-05-07 19:13
You are probably using the system pinch gestures? You need to disable them if you want to use 4 finger tap reliably in BTT. (You can re-configure them in BTT afterwards).

Unfortunately BTT can't know about the state of the system gestures.

**Comment by mcarreira** [comment] 2017-05-07 21:13
Thats not the case, I have disabled these system gestures. I have other system gestures enabled (such as "Swipe left from right edge with two fingers"), but not the "Pinch/Spread with thumb and 3 fingers". Should ALL system gestures be disabled??

**Comment by fifafu** [comment] 2017-05-07 21:26
Hey,

No, the swipes should be fine unless they cause problems!

However I can't reproduce the issue if the "pinch/spread" gestures are configured in BTT. Does this happen all the time?

**Comment by mcarreira** [comment] 2017-05-07 21:36
When I "Pinch", the 4 finger tap happens almost every time. When I "Spread" it does not happen as likely. Is there a way to get a log or something so I can send it to you?

**Comment by fifafu** [comment] 2017-05-07 21:43
Yes, you can go to the About tab in BTT, then press the "Export Debung Information" button. It will create a folder "BetterTouchToolDebug" that could be helpful (send to boastr.net@gmail.com). However I won't be able to look into it until tomorrow.

Does this also happen if you pinch a bit slower? Or is it only happening for relatively fast pinches?

**Comment by mcarreira** [comment] 2017-05-07 21:58
Yup, that's it. When I pinch slower it works. When I pinch faster, then a 4 finger tap is recognised instead of the pinch.

Maybe you could detect if the fingers have moved and if so then it's not a tap? I mean, when I perform a tap the fingers are relatively in the same position when I touch the trackpad and when I lift my fingers.

**Comment by mcarreira** [comment] 2017-05-11 19:52
So were you able to replicate the issue or you need the logs? Thanks, cheers and congrats for the great tool.

**Comment by fifafu** [comment] 2017-05-11 20:19
Didn't have time to look into it, but I think I know what causes the issue. I'll try to adjust the parameters a bit soon!

**Comment by fifafu** [comment] 2017-05-25 16:01
Would be great if you could test alpha version 2.14 (get via "Check for Alpha Versions" in the menubar menu). I think this should be fixed. If not please comment here, then I'll reopen the issue.

**Closed by fifafu** 2017-05-25 16:01 UTC

**Comment by mcarreira** [comment] 2017-05-25 20:12
Hello, thanks for the fast fix! Yup, its much better now. Kudos for your great work.
