### ISSUE TITLE
2f swipe stop working

### ISSUE THREAD

**Issue by justinpma** [fifafu/BetterTouchTool#1296] opened 2017-08-07 23:01 UTC
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
2f swipe from bottom and top doesn't work and don't show up on live feed

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

trackpad

#### Device information:

Type of Mac: 2016 15"
macOS version: 10.13.b4
BetterTouchTool version: latest beta

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by tonynguyen1901** [comment] 2017-08-08 04:45
same I swipe from top to command+W to close windows but now it doenst work

FYI the 2 fingers swipe from left and right edge as well

**Comment by fifafu** [comment] 2017-08-08 05:58
That's true. It's caused by the improved thumb / accidental touch recognition. I'll add an exception for these gestures.

**Comment by tonynguyen1901** [comment] 2017-08-08 06:07
so is there gonna be an update soon or it should be a few weeks? 

p/s: cant believe I'm actually communicating with Andreas in real time lol. Great app man!

**Comment by fifafu** [comment] 2017-08-08 06:21
It will probably come tomorrow! :-)

**Comment by tonynguyen1901** [comment] 2017-08-08 06:23
Cheers!

**Comment by ignaciobarrena** [comment] 2017-08-09 12:23
yep, 2f swipe from top or bottom is broken v2.273 macOS 10.12.6 rMBP 2015 13"

**Comment by fifafu** [comment] 2017-08-09 20:21
should be fixed now in v2.280 alpha!

**Closed by fifafu** 2017-08-09 20:21 UTC
