### ISSUE TITLE
BetterTouchTool causing system crash/reset (?)

### ISSUE THREAD

**Issue by Deskimo** [fifafu/BetterTouchTool#1393] opened 2017-08-29 01:12 UTC
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

My system has rebooted randomly a couple of times this morning (since updating BTT) and based on logs i think its BTT doing it. This is the second crash so my system had just been restarted fresh an hour before.

#### Device information:

Type of Mac: Macbook Pro
macOS version: 10.12.6
BetterTouchTool version: 2.295

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Logs just before crash occurred ...

Aug 29 09:24:47 Davids-MBP BetterTouchTool[874]: notify name "com.apple.system.powersources.timeremaining" has been registered 20 times - this may be a leak
Aug 29 09:25:17 --- last message repeated 17 times ---
Aug 29 09:25:19 Davids-MBP BetterTouchTool[874]: notify name "com.apple.system.powersources.timeremaining" has been registered 20 times - this may be a leak
Aug 29 09:25:20 Davids-MBP BetterTouchTool[874]: notify name "com.apple.system.powersources.timeremaining" has been registered 20 times - this may be a leak
Aug 29 09:25:50 --- last message repeated 16 times ---
Aug 29 09:25:50 Davids-MBP BetterTouchTool[874]: notify name "com.apple.system.powersources.timeremaining" has been registered 20 times - this may be a leak
Aug 29 09:25:58 --- last message repeated 4 times ---
Aug 29 09:25:58 Davids-MBP UserEventAgent[41]: assertion failed: 16G29: com.apple.telemetry + 58408 [165E935B-9099-32D4-945F-270EC2E89A29]: 0x5
Aug 29 09:25:58 Davids-MBP BetterTouchTool[874]: notify name "com.apple.system.powersources.timeremaining" has been registered 20 times - this may be a leak
Aug 29 09:26:53 localhost bootlog[0]: BOOT_TIME 1503962813 0

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by Deskimo** [comment] 2017-08-29 02:37
PLus all crash reports from BTT though the system crash seems to have stopped BTT from crashing (assuming it was going too!)

[AllBTT-crashes.zip](https://github.com/fifafu/BetterTouchTool/files/1258944/AllBTT-crashes.zip)

**Comment by fifafu** [comment] 2017-08-29 06:50
I don't think your system crashes are caused by BTT but rather that BTT also crashed due to some system failure.

However to be sure, can you quit BTT and check whether it still happens?

**Comment by Deskimo** [comment] 2017-08-29 08:39
it's hard to say isn't it (i find os x logs confusing so cant make out what happened at time of crash) but i haven't had a crash again today and BTT is not running. I'll turn it on now and see if we get the crash again. standby.

**Comment by Deskimo** [comment] 2017-08-29 08:40
while we're conversing i must say i LOVE the app!

**Comment by fifafu** [comment] 2018-02-03 09:28
I'm currently closing some older issues, in case this still doesn't work correctly, please comment again or open a new issue.

I'll have much more time moving forward as I'm now self-employed. I'm sorry I was not able to solve/reply to this earlier.

**Closed by fifafu** 2018-02-03 09:28 UTC

**Comment by Deskimo** [comment] 2018-02-03 22:59
ok cool - i am using BTT happily without crashes. thanks - its exciting to see little applets (like crypto currency trackers) appearing. BTT + these apps and the touch bar feels useful! 

It woud be great to see some blog posts btw showing what canb e done with BTT - it feels like there must be so many features i havent fully comprehended and understood how it can help.
