### ISSUE TITLE
Please add "1 Finger Force Click"-Gesture

### ISSUE THREAD

**Issue by tripel-J** [fifafu/BetterTouchTool#141] opened 2016-12-20 23:42 UTC
I could for example use the "1 Finger Force Click"-Gesture to open links in new tabs in Safari by using a force-click with one finger. 

If I would turn off ForceTouch in macOS Trackpad-Settings, it would not interfere with the default settings of a single finger force click.

**Comment by pallavmac** [comment] 2016-12-21 06:59
Unfortunately single click force touch is currently not possible. The problem is that there is no viable option to block the click that is produced by the system. This means a single click force touch would always also trigger a left-click, which makes it quite useless. Andreas can not block this because he cannot see whether the user is about to do a force click or a normal click :-(

**Comment by fifafu** [comment] 2016-12-21 08:18
Closing, see #88

**Closed by fifafu** 2016-12-21 08:18 UTC

**Comment by fifafu** [comment] 2017-11-19 22:33
I have added a single finger force-click with the latest alpha (2.315). It works great as cmd+click to open a new tab in browsers :-) (although many use cases are tricky to realize because of the mentioned left-click that always happens)

**Comment by tripel-J** [comment] 2017-12-01 12:25
"Single Finger Force Click" works great for producing a CMD+click in Safari, if the systemwide ForceTouch-function is turned of in system preferences. But I am missing a haptic feedback for the single finger that I am getting with the "2 Finger Force Click" under the same circumstances.

**Comment by fifafu** [comment] 2017-12-01 13:20
Oh that's a great point. I'll enable the haptic feedback in that situation with the next version!!

**Comment by tripel-J** [comment] 2018-01-25 15:26
Did you enable it? I just installed the next version and it still doesn't give a haptic feedback for me with the "Single Finger FORCE Click".
