### ISSUE TITLE
Mouse drag started when clicking during cursor movement

### ISSUE THREAD

**Issue by fastred** [fifafu/BetterTouchTool#1580] opened 2017-10-04 07:54 UTC
#### Description of bug/feature request/question:

Steps to reproduce:

1. Launch Tweetbot.
2. Click on a tweet while moving the cursor at the same time.

Expected result:
Clicking should be recognized as clicking.

Actual result:
Clicking is recognized as dragging. Sometimes the dragging continues for a few seconds even though my trackpad is not pressed anymore and the only way to stop it, is to actually drop an element on some window.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Tested on Magic Trackpad. Not sure if it's Magic Trackpad-specific.

#### Device information:

Type of Mac: iMac (Retina 5K, 27-inch, Late 2015)
macOS version: 10.12.6
BetterTouchTool version: 2.310

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

The report is for Tweetbot but I'm **observing the same issue in Terminal.app too.** I think I first saw this issue during last 1-2 months.

##### Videos

![unwanted_drag](https://user-images.githubusercontent.com/197767/31164972-7ea1a82a-a8e9-11e7-8f50-966c459806c0.gif)

![drag3](https://user-images.githubusercontent.com/197767/31165631-1a946342-a8ec-11e7-9a9f-e0fd979ba987.gif)

**Comment by neilpride** [comment] 2017-10-04 17:46
I've got the same problem with the Dashboard, when BTT is working.
Very annoying.

**Comment by fastred** [comment] 2017-10-04 17:51
Yeah, I see it in some other apps too, e.g. in Xcode text gets selected and/or scrolled. I don't know macOS APIs but it seems related to some API that many, but not all, apps use.

**Comment by fastred** [comment] 2017-10-05 09:33
FWIF this bug is not present in the version 2.297 (676).

**Comment by p96** [comment] 2017-10-05 16:30
I'm still seeing it in Dashboard with version 2.310 (687). It makes the Dashboard very annoying to use since the tools relocate when I try clicking on the desktop to exit the Dashboard.

**Comment by ben174** [comment] 2017-10-05 17:18
Yea, I opened #1578 which seems to be this same issue.

**Comment by ben174** [comment] 2017-10-05 21:25
I believe this is related to the 'Shake mouse pointer to locate' accessibility option. As a temporary fix, disable this option in System Preferences -> Accessibility

**Comment by p96** [comment] 2017-10-05 21:51
Thank you. Disabling the shake to locate accessibility feature significantly reduces the chances of relocating a Dashboard widget, but it still happens (around 1 in 10-20 times).

**Comment by fifafu** [comment] 2017-10-05 21:58
That's interesting, I'll try to figure out what's going on this weekend! If you find anything else please report here.

**Comment by fastred** [comment] 2017-10-05 22:07
@fifafu thanks and good luck hunting the bug!

**Comment by clundie** [comment] 2017-10-06 16:59
I'm getting this a lot in Terminal.app. It reproduces fairly easily by clicking inside the Terminal window and then clicking the menu bar at the top of the screen. It will often select (highlight) a large amount of text inside the Terminal and scroll up a few lines. Problem goes away if I disable BTT completely, or just for Terminal.

**Comment by ostsjoe** [comment] 2017-10-09 17:45
I'm getting the same behaviour, especially apparent in chrome for me, however I do not have ''Shake mouse pointer to locate'. I can repro nearly 100% if I slowly slide the mouse by to click on a button. BTT 2.310. Clicks work normally with BTT shutdown.

**Comment by ben174** [comment] 2017-10-11 18:39
Bump on this issue - it's making BTT unusable for me, and rolling back to a previous version would require me to recreate my settings :(

**Comment by fifafu** [comment] 2017-10-11 19:43
@ben174 unfortunately I haven't been able to reproduce it yet (it doesn't seem to affect all systems, I assume it may be a conflict with some other software)

However BTT keeps copies of your previous settings in ~/Library/Application Support/BetterTouchTool  so you can downgrade easily (just rename the the files with the oldversionbackup extension for the version you want to restore)

**Comment by ben174** [comment] 2017-10-11 19:50
Hmm, ok some key items about my system:

* Dual 4k Monitors hooked up via USB-C to a 13" MacBook Pro
* Occurs on both Mouse and Trackpad. I removed all the gestures I have configured for both devices, and the problem persists. 
* Only other configuration left in BTT is three keyboard shortcuts, which I doubt would be related since this is a mouse-specific issue.
* 1Password is installed (1Password has a known issue causing clicks to behave weirdly in Chrome - but this issue seems to occur outside of Chrome, so it seems unlikely)

Anyone else experiencing this issue have anything in common with the above?

**Comment by somebee** [comment] 2017-10-12 12:10
This happens for me as well. It's the issue I mentioned in #1577. For me it only happens on trackpad (I use a Logitech Mx Anywhere 2 as external mouse). The annoying thing here is that I have no gestures or anything defined for Trackpads. I only use it for TouchBar.

**Comment by fifafu** [comment] 2017-10-16 15:06
I have identified the issue and believe it is a macOS bug. I have reported it to Apple.

However I have found a workaround that will prevent this. It will be included in the next update ( >= 2.312 )

**Closed by fifafu** 2017-10-16 15:06 UTC

**Comment by ben174** [comment] 2017-10-19 18:54
FYI, looks like when I do not use display scaling on my 4k monitors, this issue goes away.

**Comment by ben174** [comment] 2017-10-19 19:22
Strike that, the behavior has returned, with all of my displays not using display scaling :( 

@fifafu , any idea when the next update will be published?

**Comment by fifafu** [comment] 2017-11-05 12:59
Could you check whether 2.313 alpha fixes this?

**Comment by ben174** [comment] 2017-11-07 19:30
Seems to have fixed it! Haven't been able to recreate after about 20 minutes of usage (usually would have occurred by now - especially when I'm _trying_ to cause it. 

Care to detail what the fix was? Just curious.

Thanks so much for addressing this!

**Comment by fifafu** [comment] 2017-11-07 19:45
It was a very specific bug in the CGEventTap API in macOS. I believe this must have been introduced in 10.12.6 or 10.12.5. I have reported it to Apple.

The workaround was easy, but finding this issue was a nightmare....

**Comment by p96** [comment] 2017-11-07 22:39
It does seem to be fixed with that alpha. Thanks!

**Comment by fastred** [comment] 2017-11-14 20:33
@fifafu Thanks for fixing this!
