### ISSUE TITLE
Touch Bar Behavior setting not working for VS Code

### ISSUE THREAD

**Issue by fitzage** [fifafu/BetterTouchTool#2238] opened 2018-03-13 18:13 UTC
#### Description of bug/feature request/question:

The Touch Bar Behavior settings don't work for Visual Studio Code. I set it to display the BTT bar (with control strip) in VS Code, but it shows the app default toolbar instead, which is essentially useless. I also tried without the control strip and got the same result.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: 2016 13" MacBook Pro Touch Bar
macOS version: 10.13.3
BetterTouchTool version: 2.403 (754)

**Comment by fitzage** [comment] 2018-03-13 18:40
For now my workaround is just to make everything show when pressing option, which also made me realize that's a better solution for a lot of apps than having to either close BTT to get to system functions or hit the BTT button to open them.

**Comment by fifafu** [comment] 2018-03-31 14:53
Mh I just tried to reproduce this (sorry for the delay), but it seems to be working fine here. 

![image](https://user-images.githubusercontent.com/8820811/38164381-e79c77fa-3503-11e8-9837-03e78075a503.png)

I'm closing here as I haven't had other similar reports, but if you still can't get it to work please let me know, then I'll reopen.

**Closed by fifafu** 2018-03-31 14:53 UTC

**Comment by fitzage** [comment] 2018-04-02 23:03
In one of the recent updates I saw something that seemed like it could have been related, but hadn't tested again yet. The issue appears to be resolved.

**Comment by fitzage** [comment] 2018-04-05 21:28
@fifafu Aha! I don't know if this was true before, but here's what's happening now:

1. If I use command-tab to switch to VS Code, it shows the BTT bar by default like it's set to.
2. If I switch to VS Code by clicking into it, it does not show the BTT bar by default.
