### ISSUE TITLE
Neither Mouse nor Trackpad input works

### ISSUE THREAD

**Issue by darrenoia** [fifafu/BetterTouchTool#1816] opened 2017-12-01 03:48 UTC
It's frustrating to see that the Mac OS 10.13.2 problem is considered resolved, since I can't make 2.318 work with it at all. Keyboard commands work. But Magic Mouse and Magic Trackpad both act as if BTT isn't enabled at all. No ability to do multiple finger force clicks, no ability to use swipes for anything beyond Mac basics.

**Comment by fifafu** [comment] 2017-12-01 07:39
Maybe you are still on the old developer beta? The issue is definitely resolved in the new developer betas of macOS.

**Comment by darrenoia** [comment] 2017-12-01 20:32
I was on public beta but had stopped updating. After a glitch with the update to the latest PB, I just reverted to the regular release and all is well again. Thank you.

**Closed** 2017-12-17 22:46 UTC
