### ISSUE TITLE
Dragging Lag on macOS Sierra / iMac 5K

### ISSUE THREAD

**Issue by osmannuriguler** [fifafu/BetterTouchTool#79] opened 2016-12-11 00:13 UTC
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
I have been using BetterTouchTool for a long time and I love it! It is a must have app for me and using all the time with so many gestures! After I switched to 5K iMac, I am experiencing a dragging lag on Magic Mouse 2 and Magic Trackpad 2. When I quit btt, everything goes to normal. Also you can see in the video below. 

**What kind of Mac are you using?**

iMac (Retina 5K, 27-inch, Late 2015)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Magic Trackpad 2 and Magic Mouse 2

**Which version of macOS are you running?**

macOS Sierra 10.12.1

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

You can find the video where the problem is experienced on this link;
https://www.dropbox.com/s/uz17teaghgqgu2k/Dragging%20Lag.mov?dl=0

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by osmannuriguler** [comment] 2016-12-15 08:24
Really? Nobody cares about this issue?

**Comment by fifafu** [comment] 2016-12-15 08:27
Unfortunately i'm unable to reproduce it on my 5k iMac. 🙁
Does this only occur when the magic trackpaf is connected over bluetooth or also vis usb?

**Comment by osmannuriguler** [comment] 2016-12-26 18:01
Hi,
I have noticed that the issue causes by the "snap areas" feature. I was using it on my old Mac so set for the new one. It is really useful but it causes lag now. When I delete all the Snap areas, everything goes to normal. When I create a new snap area, dragging lag starts again :(

**Comment by fifafu** [comment] 2016-12-26 19:47
Ah, that's good to know! I'll check if this can be improved  :-)

**Comment by stanfordquan** [comment] 2017-01-17 23:47
I reproduced the bug! Using Macbook Pro 13" with LG 5k. Snap area causes lags lasting around a second, specifically when moving / resizing windows. Using macOS Sierra 10.12.2. This, I guess, is unrelated to specific trackpad and mouse.

Is there away to disable the snap area animation and just use the keyboard shortcut?

Thanks a ton!

**Comment by osmannuriguler** [comment] 2017-01-18 07:34
I think this is related to the resolution of the display. I am experiencing this problem on my 5K iMac but my Macbook air 13" which has same version of OS and same version of BTT with exact same settings, it works flawlessly. No lag at all with the snap areas or something else. 

I am not sure is there any way to turn off snap areas feature using a keyboard shortcut but actually I dont want to keep it turned off. Because I use it all the time. Very useful!

(If you want to turn off snap areas completely, there is an advanced settings section in the preferences.) This will solve the problem but as I said, this feature is such useful that it should not be turned off.

Whole app is working a bit slow on HiDPi / higher resolutions. It needs to be optimized for these kind of machines.

Thanks!

**Comment by fifafu** [comment] 2017-01-29 17:52
Hey,

one idea: Could you try if activating this option in the advanced settings helps a bit?

![image](https://cloud.githubusercontent.com/assets/8820811/22406483/1d5f7f90-e654-11e6-88f4-bf47ad55fa25.png)

**Comment by osmannuriguler** [comment] 2017-01-29 18:38
Hi, I tried it but unfortunately nothing changed :/

**Comment by stanfordquan** [comment] 2017-01-30 05:23
Can confirm, nothing changed from that suggestion. Thanks for taking a look into this!

**Comment by jasonchoimtt** [comment] 2017-07-30 09:38
Hi, I also experience a similar effect. I notice a lag when the polling rate of my mouse is too high (say 500 Hz), but the lag goes away if the polling rate is lower (say 125 Hz). In either case the lag disappears if I turn off the snap area feature.

I'm on Sierra 10.12.6, on a 2017 MacBook Pro 13" with touch bar.

**Comment by adamtmitchell** [comment] 2017-08-15 01:21
I had the same issue right up to 2.270, but having updated to the latest alpha (2.281) it seems the performance improvements to snap areas mentioned in the changelog have resolved this. Thank you!

**Comment by oliverjc** [comment] 2017-09-03 13:57
I'm also having the same issue. Disabling the snap areas feature fixes this.

**Comment by fifafu** [comment] 2017-09-03 14:04
@oliverjc this should be resolved in the current versions, try to update.

**Closed by fifafu** 2017-09-03 14:04 UTC
Labels: bug, Need other people who can reproduce the issue

**Comment by oliverjc** [comment] 2017-09-03 14:46
I'm on 2.297, is that not the most recent version?

**Comment by geekdada** [comment] 2017-10-25 02:37
I'm on 2.310, but it seems unsolved.

**Comment by accordionnoir** [comment] 2017-11-27 19:59
I seem to be having this same drag lag problem. Using BetterTouchTool 2.313.

Any other reports like mine?

**Comment by wooliudo** [comment] 2018-01-13 01:58
i find that with BTT on, dragging icons on desktop would spike the CPU usage of windowserver up to 100% and result serious lag. When BTT's off, it usually stays below 46% max.
