### ISSUE TITLE
Screenshots colors are whiter

### ISSUE THREAD

**Issue by universvm** [fifafu/BetterTouchTool#2378] opened 2018-04-03 12:52 UTC
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
When taking a BTT screenshot, all the colors seem to be whiter than usual. I attached 2 screenshots in the Additional Information section.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
BTT Screenshot image

#### Device information:

Type of Mac: MacBook Pro 2016
macOS version: 10.13.4
BetterTouchTool version: 2.423 (Alpha) [although I tried it before updating to the alpha]

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I don't remember this happening before. I suspect it could be the latest update.
 
The resulting screenshots from BTT:
<img width="1642" alt="btt" src="https://user-images.githubusercontent.com/17524568/38250010-84ce06ea-3745-11e8-9cf0-f9fbef20a302.png">

and the second one is a native MacOS screenshot of the BTT window after taking a screenshot:

<img width="1666" alt="native" src="https://user-images.githubusercontent.com/17524568/38250057-ab978e5e-3745-11e8-8bdb-3cd2b89778e9.png">
---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment] 2018-04-03 13:17
Have you already tried to restart your machine? (BTT just calls the system screenshot utility thus it may be some strangeness with that)

I can not reproduce the issue here.

**Comment by universvm** [comment] 2018-04-03 13:22
I did restart my system. I have screenshots from basically everyday, and only after updating they started to be whiter. 

Not sure if it can help but opening the image on photoshop corrects the colors automatically (somehow), however preview shows it as whiter and it is whiter when uploading to websites as well.

**Comment by universvm** [comment] 2018-04-03 13:34
I think I am getting closer to what may be causing this: the bug is only triggered when you press "Save" in the interface above. If you click 'X' instead, colors are not affected. 

I believe it is saving the image twice, once when the screenshot is taken, and the second time when pressing "save" which changes the colors.

(Unrelated to this, I still don't understand the point showing the dialog image "Saved this screenshot was saved  [...]". It shouldn't be hard to press "save" and close all the windows. The image is saved even if you don't press save so the dialog is not really useful.)

**Comment by Shnub** [comment] 2018-04-03 14:38
This is a color space issue. The "whiter" screenshot is not tagged with a color space, causing the Preview app (and macOS in general) to choose some profile at random for display, in my case "Calibrated RGB Colorspace". This causes the shift in brightness. The correct screenshot is tagged with sRGB, which is what it should be for standard use cases.

The reason why Photoshop is able to correct the issue is because it detects the missing embedded profile on opening and, by default, assigns sRGB to the image.

I presume the cause of the problem is that BTT forgets—or somehow does not manage—to tag the saved image properly.

**Comment by fifafu** [comment] 2018-04-03 14:51
@Shnub I think you are right - chrome also displays the png correctly which is why I was unable to reproduce it here. I'll check what is wrong (apparently it started with 10.13.4, so maybe something with color space handling has changed)

**Comment by fifafu** [comment] 2018-04-04 12:49
It's really weird, I still can't seem to reproduce this here and the sRGB profile seems to be set correctly...

One question: does this only happen when your Macbook is connected to an external monitor, or always?

**Comment by universvm** [comment] 2018-04-04 12:57
Nope, I don't use any external monitors.

I think I understood what is causing the problem: somehow if the color profile for "f.lux" is activated, in the system settings it causes this bug to arise. Changing to Color LCD as profile "fixes it".  I never had problems with this though...

There are a few things I still don't understand like why is the bug only caused when you click "save" and not when you exit by pressing "x". Does BTT save the picture twice?

**Comment by fifafu** [comment] 2018-04-04 12:59
Yep, save basically makes sure to write all possible changes made after taking the screenshot, so when pressing that button it will override the original screenshot.

The f.lux hint is very helpful, I think that will help me fix it!

**Comment by universvm** [comment] 2018-04-04 13:00
I did however try to quit flux when reproducing this. Apparently quitting f.lux does not change the color profile back to Color LCD.

**Comment by fifafu** [comment] 2018-04-04 13:50
Mh then I think I'm currently out of ideas as I'm now even re-tagging the screenshots with the sRGB color space (and unfortunately I'm still unable to reproduce it here even with f.lux running 😕). 

One more question: does this happen for all screenshots, or only with specific apps?

**Comment by universvm** [comment] 2018-04-04 14:17
Since you said that you ran f.lux, I tried deleting the profile while f.lux was not running. It seems to have fixed the issue so now I am able to take screenshots normally. 

Weird issue... In any case, thank you so much for your help!

**Comment by fifafu** [comment] 2018-04-05 15:40
Ok, I'm closing here for now, if it happens again please let me know.

**Closed by fifafu** 2018-04-05 15:40 UTC
