### ISSUE TITLE
Clicking Bug

### ISSUE THREAD

**Issue by pallavmac** [fifafu/BetterTouchTool#119] opened 2016-12-15 04:50 UTC
#### Description of your bug/question/feature request...:
With BTT active, if the user is using one finger to click and another finger to move the mouse or drag something, then it doesn't work! The user needs to first click, then place the other finger and move. Usually both fingers are touching the trackpad and one finger moves to the file, the other finger clicks and holds and the original finger starts moving. Quitting BTT allows this to work. Please fix this bug as it is a fundamental drag function that doesn't work and is coming in the way in daily interaction with the Mac. Shall have to use the old version of BTT until then. Please tell me if you need a video demonstration of this. 

**What kind of Mac are you using?**
MPB 15" touchbar

**Which input device is affected by this?**
Built-in Trackpad

**Which versions of macOS and BetterTouchTool are you running?**
MacOS 10.12.1
BTT 1.97

**Comment by fifafu** [comment] 2016-12-15 07:33
Are you sure this ever worked with BTT? (If so, which version?
I currently think that's not fixable and has always been like this, however I may have misunderstood something :-)

**Comment by pallavmac** [comment] 2016-12-15 07:38
Yes. Just checked. It worked up till version 1.963 then stopped working in version 1.964.

**Comment by fifafu** [comment] 2016-12-15 07:42
Weird, in many cases BTT has to block that behavior to prevent clicks while doing some gestures.
Could you send me an export of your current gestures to boastr.net@gmail.com?

**Comment by pallavmac** [comment] 2016-12-15 13:41
Sure. All gestures worked on both the new and old versions. 
[BTT Gestures.zip](https://github.com/fifafu/BetterTouchTool/files/654776/BTT.Gestures.zip)

**Comment by kaloprominat** [comment] 2016-12-15 21:06
i can confirm that i've noticed similar bug occurred between those version

**Comment by kaloprominat** [comment] 2016-12-15 21:08
to be more exact: tiptaps not working correctly. what information would be helpful?

**Comment by fifafu** [comment] 2016-12-15 21:13
@kaloprominat that sounds like something different, gave a look at #18

**Comment by kaloprominat** [comment] 2016-12-15 21:24
@fifafu not sure it related to #18. i clearly see that on version 1.963 tiptaps works perfectly, and on 1.964 very glitchy, almost not working regardless of side and maximum allowed distance. i can capture screen with "live view", for example.

**Comment by pallavmac** [comment] 2016-12-24 15:13
@fifafu I was wondering wether you are working to fixing this. I am stuck on version 1.963 because of this critical dragging issue which interrupts basic Mac functions if I use latest version. But version 1.963 has really bad palm rejection which is good in 1.977. Could you maybe add some sort of option in version 1.978 which allows drag with two finger on the trackpad to work? My tiptaps never get activated when I'm dragging with one finger and clicking and holding with the other. I hope there's a workaround to this because everything is working great in 1.963 except for palm rejection. And I don't think the dragging issue is to do with palm rejection because 1.964 doesn't have the new palm rejection yet the drag doesn't work on this. Thanks again. Really hoping this can be fixed.

**Comment by fifafu** [comment] 2016-12-24 15:15
Would you be able to do a short screen recording of the live view in BTT? (Because unfortunately I haven't been able to reproduce the issue, but maybe I misunderstood something)

**Comment by fifafu** [comment] 2016-12-24 15:24
Does the bug also occur with a new/empty gesture preset?

**Comment by bricktop-at** [comment] 2016-12-24 15:26
Hi!

Same here (MBP mid 2009, Sierra 10.12.3 Beta (16D17a) ... with BTT enabled i have to lift the finger instead of being able to tap with a second finger.
Hope I can explain this properly: I use my index finger to move the cursor and the middle finger to tap on links, icons and so on. With BTT disabled I don't have to lift my index finger and the middle finger taps are working. BTT seems to interfere somehow as the middle finger taps aren't recognized as long as the index finger is still resting on the touchpad

**Comment by pallavmac** [comment] 2016-12-24 15:26
Live view doesn't show it. Here's the issue:
(File was too big for GitHub so I put it on google drive. You may need to download the video):
https://drive.google.com/file/d/0Bz2F8f8WJhHtWFBGcTFmTTlfazg/view?usp=sharing
Thanks for reviewing it!

**Comment by fifafu** [comment] 2016-12-24 15:36
So weird, I still can't reproduce that behavior :-( But thanks a lot for the video!
Could you send me your com.hegenberg.BetterTouchTool.plist from ~/Library/Preferences/ ? Maybe it's a specific combination of settings that causes this.

**Comment by pallavmac** [comment] 2016-12-24 15:39
Here it is:
[com.hegenberg.BetterTouchTool.plist.zip](https://github.com/fifafu/BetterTouchTool/files/671820/com.hegenberg.BetterTouchTool.plist.zip)

**Comment by fifafu** [comment] 2016-12-24 15:40
Aha! Indeed I can reproduce it with that plist. I'll check what's wrong!

**Comment by pallavmac** [comment] 2016-12-24 15:42
Thank so much! Sorry for the trouble. I realise this issue was not something that affected everyone. Shall wait for future updates! And congratulations by the way :)

**Comment by fifafu** [comment] 2016-12-24 15:42
Does enabling "Thumb / Palm Handling" change the behavior?

![image](https://cloud.githubusercontent.com/assets/8820811/21467713/f4e259b6-c9f7-11e6-970f-2741a9eac22d.png)

**Comment by pallavmac** [comment] 2016-12-24 15:44
Nope...

**Comment by fifafu** [comment] 2016-12-24 15:47
Weird, that seems to fix it on my machine - could you try what happens when you rename the plist to something else while BTT is closed? (BTT will then create a new one, so we'll know for sure whether it's a setting in the plist that causes it)

Best also create an export of your current setup before doing this.

**Comment by pallavmac** [comment] 2016-12-24 15:48
I attached screenshots of all my settings in case that would be helpful. (Version 1.977)
<img width="1127" alt="screen shot 2016-12-24 at 11 45 16 pm" src="https://cloud.githubusercontent.com/assets/9432573/21467753/2361160c-ca33-11e6-9730-6356e8654402.png">
![Uploading Screen Shot 2016-12-24 at 11.45.18 PM.png…]()
![Uploading Screen Shot 2016-12-24 at 11.45.21 PM.png…]()
![Uploading Screen Shot 2016-12-24 at 11.45.23 PM.png…]()
![Uploading Screen Shot 2016-12-24 at 11.45.24 PM.png…]()
![Uploading Screen Shot 2016-12-24 at 11.45.26 PM.png…]()
![Uploading Screen Shot 2016-12-24 at 11.45.28 PM.png…]()
![Uploading Screen Shot 2016-12-24 at 11.45.29 PM.png…]()

**Comment by pallavmac** [comment] 2016-12-24 15:52
Wow. That works! I deleted the plist file. And then opened version 1.977. My gestures are all still there too.

**Comment by fifafu** [comment] 2016-12-24 15:54
Thanks for testing! Ok, I'll compare your previous plist to the default settings and check what setting is causing it!

**Comment by pallavmac** [comment] 2016-12-24 15:55
Here I have uploaded my old plist and new plist file. Maybe you could compare the 2 and see what changed. Thanks again.
[Plist Files.zip](https://github.com/fifafu/BetterTouchTool/files/671827/Plist.Files.zip)

**Comment by pallavmac** [comment] 2016-12-24 16:19
@fifafu Such a silly mistake! You were right. Enabling "Thumb / Palm Handling" does change the behaviour! I thought you said "Thumb / Palm Filtering". I have reloaded my old plist back and everything works fine and my settings are back to my old versions. Maybe in the next update you could make everyone's "Thumb / Palm Handling" default to ticked. You can probably close this issue now.

**Comment by pallavmac** [comment] 2016-12-24 16:20
@kaloprominat enable "Thumb / Palm Handling" in Advanced Settings>Trackpad>Palm & Thumb Recognition. That fixes it.

**Comment by fifafu** [comment] 2016-12-24 16:21
Thanks! I'll fix the bug with the next update. It should also work when Thumb / Palm Handling is not activated. Closing for now!

**Closed by fifafu** 2016-12-24 16:21 UTC

**Comment by bricktop-at** [comment] 2016-12-26 13:22
Still having the issue unfortunately, latest alpha version of BTT... enabling/disabling "Thumb / Palm Handling" doesn't change anything and deleting the plist file also didn't do anything....
Any ideas maybe?

**Comment by pallavmac** [comment] 2016-12-26 14:22
@bricktop-at you might wanna try changing the distance settings for tip taps. Because the way you use your trackpad to tap is exactly the same way tip taps work. Maybe @fifafu you could add an option to disable BTT from reserving the tip tap gesture if the user has not set a tip tap gesture. But by making the max distance 0, the same thing should work @bricktop-at .
<img width="1127" alt="screen shot 2016-12-26 at 10 20 03 pm" src="https://cloud.githubusercontent.com/assets/9432573/21483204/754f673e-cbb9-11e6-9342-bad19e27a31f.png">

**Comment by bricktop-at** [comment] 2016-12-26 16:52
Thanks a lot for the suggestion, but that also didn't change anything unfortunately...

**Comment by MichaelSiddi** [comment] 2017-01-09 20:39
Hi, I've tried all the suggestions with no luck :-(. 
I'm experiencing the issue on a tbrMBP 15''.

**Comment by fifafu** [comment] 2017-01-09 20:45
So there are definitely situations where BTT needs to block clicks that include two fingers. E.g. when using the Tip Tap gesture. Are you maybe using that gesture? If not, it'd be great if you'd attach an export of your setup (via the export preset button), then I'll look into it.

**Comment by MichaelSiddi** [comment] 2017-01-09 21:08
I only have one gesture set up, Three Fingers Tap for MiddleClick.
Thank you very much for looking into this, I love BTT (and the touch bar support!)

[BTT-Default.zip](https://github.com/fifafu/BetterTouchTool/files/694645/BTT-Default.zip)

**Comment by kaloprominat** [comment] 2017-01-16 17:04
@fifafu for me, actually helped disabling "Thumb / Palm Handling" on version 1.989
