### ISSUE TITLE
Advanced settings of TB Widget Emoji shows Shell dialog. Duplicated items on left panel.

### ISSUE THREAD

**Issue by JulyIGHOR** [fifafu/BetterTouchTool#2031] opened 2018-01-27 17:23 UTC
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

1) Advanced settings of Emojy TB shows Shell dialog instead
2) I have two apps with same name on left panel, maybe you want to know that this bug exists

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook TB

#### Device information:

Type of Mac: Latest
macOS version: Latest
BetterTouchTool version: Latest

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Here is video: https://www.dropbox.com/s/yfc0w6ft4t3oiso/BetterTouchTool_Bugs.mov?dl=1

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment] 2018-02-02 09:18
1.) Thanks for reporting, this will be fixed in the next version!
2.) This is by design (when adding an app from the file system it is slightly different than when adding it from the list of active apps). You can delete one of them.

**Closed by fifafu** 2018-02-02 09:18 UTC
