### ISSUE TITLE
Hot keys with context-menu actions only work the first time

### ISSUE THREAD

**Issue by mark-bamberg-medfx** [fifafu/BetterTouchTool#2296] opened 2018-03-21 13:40 UTC
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I have a hotkey assigned as an application specific (MS Excel) trigger to execute two context-menu actions.  The first is "Copy"; the second is "Insert Copied Cells".

In version 2.412-2.414, this began to fail.  Version 2.415 fixed it a little.  With that version, the hotkey functions as expected but only one time; subsequent uses of the hotkey fail.  It seem like the failure is associated with moving the focus, because I was able to get it work more than once if I didn't change focus.

This is related to "#2278 Context Menu"

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard

#### Device information:

Type of Mac: Mac Pro w/Touchbar
macOS version: 10.13.3
BetterTouchTool version: 2.415

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment] 2018-03-21 13:53
Could you post a screenshot of your configuration? I can't seem to reproduce this :-(

**Comment by fifafu** [comment] 2018-03-22 12:05
This should now be fixed in v2.418.

While I couldn't reproduce it at first, it lead me to a bigger issue that I have been looking for since quite a while. So thanks a lot for reporting!

**Closed by fifafu** 2018-03-22 12:05 UTC

**Comment by mark-bamberg-medfx** [comment] 2018-03-22 13:04
I love your utility.  It is such an amazing productivity tool!
