### ISSUE TITLE
4 finger and 5 finger swipe left and right not working   in 2.4

### ISSUE THREAD

**Issue by goldsgymreview** [fifafu/BetterTouchTool#2231] opened 2018-03-13 12:12 UTC
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
4 finger and 5 finger swipe left and right not working   in 2.4
4/5 finger swipe up/down work ok. 3 finger up/down/left/right  work ok. 

Dropping down to version 2.321 restores functionality (i did not try every past version, 2.34 failed, 2.401b failed, 2.321 worked ok).

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Trackpad 

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Late 2013)
macOS version: 10.12.6 (Sierra, Not high sierra)
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment] 2018-03-13 13:29
There hasn't been a change to the gestures, so I assume it's the action you assigned that doesn't work. What are you trying to trigger using the gestures?

**Comment by goldsgymreview** [comment] 2018-03-13 13:43
![screen shot 2018-03-13 at 7 02 39 pm](https://user-images.githubusercontent.com/31108895/37344741-345b4308-26f1-11e8-9473-a52565c1243e.png)

All these are mapped to keystrokes, which are set in moom (a window management tool) to move windows to the left/right side of the screen (3 finger left/right) and to the next display (5 finger left/right). 

If i type the keystrokes directly, moom triggers the actions just fine. 

Also, I do not change any settings in btt: simply quitting btt 2.4 and replacing the executable program file in the application directory for the older version and then opening it makes everything work ok... so looks like something in the new version is causing this since that is the only variable i am changing.  To confirm this, I replaced the old version executable with the new version and the swipes stopped working again. I put back the old version and changed nothing else and the swipes work OK again.

P.S. btt is an awesome tool. Thank you so much!

**Comment by fifafu** [comment] 2018-03-16 16:07
Maybe try v2.407 alpha, I have changed some parts of the shortcut functionality in that version. (get via "check for alpha version updates")

**Comment by orphanedrecord** [comment] 2018-03-17 04:27
I believe I have the same issue using with three finger swipe left on BTT v2.405. 
I use a BTT with Moom also (nice combo!) and my trackpad gesture is set to control + option + command + left arrow … which appears to be what you are using for your 4 finger gesture issue. So it seems, the issue is not which the gesture itself, but the combination of keys we are using as triggers as fifafu mentioned.

And I agree, BTT is awesome. Thank you for a great product!

**Comment by goldsgymreview** [comment] 2018-03-17 16:07
orphanedrecord: great insight! That is exactly right... I remapped the shortcuts to something else (control+command+;) and everything works OK.

**Comment by fifafu** [comment] 2018-03-17 21:21
This should be fixed in v2.410 alpha!

**Closed by fifafu** 2018-03-17 21:21 UTC
