### ISSUE TITLE
Only show certain touchbar actions on specific website

### ISSUE THREAD

**Issue by tman0004** [fifafu/BetterTouchTool#407] opened 2017-02-04 01:04 UTC
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
So I was wondering if I can have a set of touchbar shortcuts to only show if I'm on a certain website. I would love to have this for a website like google docs. When I'm on google docs, I could make touchbar shortcuts to bold or underline something. But when I don't have the google docs website open, it should go away. 

**What kind of Mac are you using?**
MBP 15 in w/TB 2016
**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touchbar

**Which versions of macOS and BetterTouchTool are you running?**
Sierra 10.12.3 and BTT 2.02

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by cornelius1** [comment] 2017-02-05 16:07
This looks like a duplicate of issue https://github.com/fifafu/BetterTouchTool/issues/49.

**Comment by fifafu** [comment] 2017-02-05 16:08
yep, duplicate of #49. I'm working on it but it's more complicated than I had hoped to make this work reliably :-)

**Closed by fifafu** 2017-02-05 16:08 UTC
