### ISSUE TITLE
Cursor clicking problems

### ISSUE THREAD

**Issue by reallydont** [fifafu/BetterTouchTool#926] opened 2017-05-11 00:38 UTC
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
The general clicking of my trackpad has occasionally just stopped registering. I keep trying to click, and it just won't work, usually until I switch to a new app. I don't think it's a problem with my trackpad because I don't have the same problem when I turn off BetterTouchTool

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Trackpad

#### Device information:

Type of Mac: Macbook pro
macOS version: 10.12.4
BetterTouchTool version: 2.12 (631)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by mikejcooper** [comment] 2017-05-11 10:47
I'm having exactly the same issue. Running 2.12 on MBP 2016 TB. It's worth noting that the issue started after the update a few weeks ago. And if you "Disable BTT for all Apps" the issue subsides.

**Comment by planetsizebrain** [comment] 2017-05-11 11:00
I'm seeing something similar, but in my case it looks like I need to click twice. A second click usually registers correctly. If I disable BTT for all apps the problem also goes away.

I'm also under the impressing that clicking 'harder' also works better, but after some twiddling with trackpad settings I don't really see an improvement and the behaviour still remains until I disable BTT.

I'm using a recent touchbar MacBook Pro and am running OSX 10.12.4 and the problems only appeared for me after updating to this latest OSX version.

**Comment by Murgatroyd314** [comment] 2017-05-13 00:29
This may be related to issue #861.

**Comment by petersyden** [comment] 2017-05-16 07:37
Macbook Pro TB, MacOs 10.12.4, BTT 2.11

Same issue as desribed by planetsizebrain

**Comment by WelshMcSpicy** [comment] 2017-05-20 00:47
I also have to click twice most of the time, irrespective of the app that's front. Thought it might be associated with trackpad setting force click/haptic feedback. Disabled that but no change.
 
I'm on Macbook Pro, MacOS 10.12.4, BTT 2.12

**Comment by mikejcooper** [comment] 2017-05-27 10:19
## **My current fix:** 

1. Download previous version: [v2.05 Mountail Lion](https://bettertouchtool.net/releases/btt2.05_final_10_9.zip)
2. Link to old backup (auto generated by BTT): /Users/$USER/Library/Application\ Support/BetterTouchTool/bttdata2.oldVersionBackup*.rar

**Comment by fifafu** [comment] 2017-05-27 10:31
If this is still happening to you, please update to alpha version 2.17, then if it happens again try to reproduce it as often as possible. Then open the BetterTouchTool preferences and go to the about tab, click the "export debug information" button.

This will create a folder "BetterTouchToolDebug" on your desktop. It would be great if you could send me the contents to boastr.net@gmail.com.

I'm closing here and continue tracking this issue in #861

Best
Andreas

**Closed by fifafu** 2017-05-27 10:31 UTC

**Comment by WelshMcSpicy** [comment] 2017-05-28 18:43
Using this build since yesterday. The issues haven’t manifested again. Of course, this could be a placebo :)
