### ISSUE TITLE
Text pasting/insertion is slow and laggy

### ISSUE THREAD

**Issue by cleverjackal** [fifafu/BetterTouchTool#593] opened 2017-03-02 10:04 UTC
I use the shortcut **⌥U** to insert the character **Ü**. However, one thing I notices was that it's really slow. Pressing "U" five times very quickly inserts it five times instantaneously. Pressing ⌥U five times like that, however, is extremely laggy.

Is there a reason for this, or a way to prevent it? One example where this could be a problem is when typing für. I press f, and then ⌥U and then _immediately_ r, and as a result "frü" is output because it takes time for the "ü" to be pasted in.

**Comment by fifafu** [comment] 2017-03-02 20:43
The problem is that for the "Paste Custom Text Action" BTT has to do multiple things that need some delay to work correctly:

- Save what's currently in your clipboard
- Copy the text to the clipboard
- Make sure the text in the clipboard has changed (this sometimes takes a few ms)
- Send cmd+v to the system
- Restore the previous clipboard content.

Unfortunately all of this takes a while which makes the paste custom text action relatively slow (but fast enough for normal text insertion). 

However I'm currently looking into various other options that could be used for inserting single characters and could be faster in that case.

**Comment by cleverjackal** [comment] 2017-03-02 20:52
@fifafu Hey, you're back! Hope you're doing well.

I totally understand why it takes time, then. I was guessing it would be something like that. What I noticed with Keyboard Mastero though is that it has an "Insert Text by Typing" option itself – and it's instantaneous. It doesn't affect the clipboard, either. 

One key difference here: when I insert text using BTT, the "Edit" menu bar item lights up, probably because of the "Paste" action it carries out as you described. However, with Keyboard Mastero that doesn't happen. So I think Keyboard Mastero uses a different method itself.

**Comment by fifafu** [comment] 2017-03-02 20:54
Ah thanks for sharing that info!

**Comment by vgrange** [comment] 2017-04-14 23:09
Hi guys,

same issue here. I rely a lot on the "paste text" actions, and the lag is quite annoying. When I type quickly some text, the keys I type do not appear in the same order as I typed them - the ones using a "paste text" action will appear later than the others. 

+1 for finding some improvement :)

BTT is a great app, thanks for all your work! I'm a paying user for a while already.

Thanks
Vermeer

**Comment by cleverjackal** [comment] 2017-04-20 15:09
@vgrange Did you try the alpha version? It has an "insert text by typing" option, which seems to be way faster as far as I can see.

**Comment by vgrange** [comment] 2017-05-02 10:06
@cleverjackal I can't find the "insert text" action:

![image](https://cloud.githubusercontent.com/assets/10533583/25613740/9bba0ba2-2f2f-11e7-84da-8ba058c8e126.png)

here is my version:
![image](https://cloud.githubusercontent.com/assets/10533583/25613784/c0f68abc-2f2f-11e7-87ca-c08ef64537f7.png)

how about you?

**Comment by fifafu** [comment] 2017-05-03 19:04
@vgrange try updating to the latest alpha (v2.097).

I'm closing here for now, although I'm planning to further improve the type/insert text action.

**Closed by fifafu** 2017-05-03 19:04 UTC
Labels: enhancement

**Comment by cleverjackal** [comment] 2017-05-07 17:49
@vgrange It's in the "paste custom text". You actually need to click on that and from there you can configure the "insert text by typing option".
