### ISSUE TITLE
BTT keyboard shortcuts stop working after a while

### ISSUE THREAD

**Issue by mauser319** [fifafu/BetterTouchTool#56] opened 2016-12-08 14:51 UTC
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
I am using BTT to emulate Windows Key shortcuts on my Mac (i.e. Windows-Left = Maximize Window Left, etc).  On a fresh boot everything works fine, and seems to work fine for a few hours at a stretch, but after a while my shortcuts simply don't function.  A restart of BTT from the menu bar fixes the issue temporarily, but the shortcuts always stall out again.

**What kind of Mac are you using?**
Originally this issue occurred on a Late 2009 Mac Pro running OS 10.8.5.  I have since upgraded to a Late 2013 Mac Pro on OS 10.12.1.

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Keyboard only (Microsoft Comfort Curve 3000, in case that makes a difference).

**Which version of macOS are you running?**
10.12.1

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
None at this time.

Thank you in advance for any light you can shed on this!

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment] 2016-12-13 21:45
Does clicking the BetterTouchTool menubar icon also fix it or do you really need to restart BTT?

**Comment by mauser319** [comment] 2016-12-13 22:20
It looks like I do indeed have to completely restart BTT in order to get my shortcuts working again.

HOWEVER, in testing your question, I discovered that BTT doesn't stall out randomly.

I have a few applications for which I've enabled "Disable BTT For This App," because I need my chosen modifier keys for app-specific shortcuts.  It now appears that the BTT shortcuts will stop working only if I've just had one of these apps in focus first.

So, for example:

1. All my BTT shortcuts are working great.  I'm using them in Finder, Chrome, Outlook, Office, etc, with no issues.
2. I switch into Adobe After Effects, which has BTT shortcuts disabled, and work for a few minutes.
3. I now switch back into Finder, and my shortcuts don't work.
4. Switch into Outlook, still no shortcuts.
5. If I restart BTT from this point, everything will kick back into gear just fine, until the next time I bring After Effects into focus.  It doesn't matter if I interact with After Effects, or attempt to use a shortcut while After Effects is in focus; if I switch into it, that kills BTT until I restart it manually.

Thanks for the follow up!  I hope this new info is helpful.  Cheers,
-Jared

**Comment by fifafu** [comment] 2016-12-13 23:27
Abh that's interesting! Thanks for figuring that out. I'll look for a fix tomorrow.

**Comment by mauser319** [comment] 2016-12-14 00:04
Thank you so much! I'm happy to test out any other conditions that might help home in on the issue, just say the word.

**Comment by fifafu** [comment] 2017-01-21 15:59
It's a bit embarrassing but I forgot whether I fixed this or not :-)
I'm currently unable to reproduce it on my machine using Version 1.991 (alpha), does it still happen for you?

**Comment by mauser319** [comment] 2017-01-23 17:42
Oh no worries, thanks for checking in!  Indeed, unfortunately the issue is still occurring for me.  I'm on 1.963 (522) right now; shall I pop into the Alpha track do you think?

**Comment by fifafu** [comment] 2017-01-23 17:46
@mauser319 that'd be great, the current alpha should be quite stable already (I'm planning a public release for the next few days)! If it's still not fixed in the alpha, could you send me an export of your setup? (using the export button in the BTT preferenfes window)

**Comment by mauser319** [comment] 2017-01-23 17:54
No problem!  I'll take a gander right now.  Thanks a million!

**Comment by mauser319** [comment] 2017-01-23 18:01
Alrighty, I'm now running v 1.992 (584), and it seems the issue's still happening.  Curses!  I've attached my setup to this message.  Happy to help if there's anything else at all that I can provide or test.  Thanks!
[BTT_mauser319_2017-01-23.zip](https://github.com/fifafu/BetterTouchTool/files/724513/BTT_mauser319_2017-01-23.zip)

**Comment by mauser319** [comment] 2017-05-09 15:44
Hello there!

Just chiming in on this again, it looks like the issue I've been having is still present even after the most recent updates.

To be thorough, I just removed and re-added all of my shortcuts, but the behavior still happens.  I've attached my setup in case that's helpful.  Thanks in advance for any insights you may have!

Cheers,
Jared
[JFBTT_7E89DA8C-6F3C-4CFA-9687-3E2457A3E910.json.zip](https://github.com/fifafu/BetterTouchTool/files/987183/JFBTT_7E89DA8C-6F3C-4CFA-9687-3E2457A3E910.json.zip)

**Comment by yimingli** [comment] 2017-08-22 22:43
Same issue. I'm using a keyboard shortcut to trigger SmartZoom. Needs to completely restart BTT after a couple of minutes (clicking menubar icon doesn't work).

**Comment by jichan3751** [comment] 2017-09-14 05:15
Same issue also happening to me as well.
BTT is disabled for Matlab and terminal, and it seems like BTT keyboard shortcut is dead after few switches to BTT disabled apps. 
It looks like trackpad gestures are still alive after keyboard shortcut is dead.

Hope this bug is fixed soon...

My configuration exported:
[Default.json.zip](https://github.com/fifafu/BetterTouchTool/files/1301754/Default.json.zip)
I use capslock key remapped to option key, remapped by Mac OS preferences.

**Comment by fifafu** [comment] 2017-09-14 05:47
Thanks for reporting, fix will come this evening!

**Comment by ylluminarious** [comment] 2018-01-23 03:45
@fifafu This problem also seems related to [this issue.](https://github.com/fifafu/BetterTouchTool/issues/1728) The trackpad gesture for three-finger click also stops working after some time and there seems to be no indication as to why. Did you ever actually resolve this problem?

**Comment by fifafu** [comment] 2018-02-03 08:52
@ylluminarious yes I think that's a different issue

**Closed by fifafu** 2018-02-03 08:52 UTC

**Comment by ylluminarious** [comment] 2018-02-05 03:03
@fifafu Ok, thanks.
