### ISSUE TITLE
Keystroke Recording Doublepress-CMD sometimes works, sometimes doesnt (needs a pause?)

### ISSUE THREAD

**Issue by fantaaaaaa** [fifafu/BetterTouchTool#597] opened 2017-03-02 21:34 UTC
<img width="1127" alt="screenshot 2017-03-02 22 30 18" src="https://cloud.githubusercontent.com/assets/24585031/23527880/ece817ca-ff97-11e6-9c91-cec89b24457a.png">

<img width="1127" alt="screenshot 2017-03-02 22 34 13" src="https://cloud.githubusercontent.com/assets/24585031/23527986/66b08d26-ff98-11e6-8f26-73a177a2a8dc.png">

i have mapped a doublepress to cmd and a doublepress to alt to save screenshots (one for clipboard and one in a folder). alt+alt always works, but cmd+cmd sometimes does, sometimes it does not. 

i have seen this thread https://github.com/fifafu/BetterTouchTool/issues/468 and thought it might be related since i seem to be able to run the cmd+cmd strokes after waiting a few seconds after the first failed attempt.

**Comment by fifafu** [comment] 2017-03-02 21:49
Weird, could you try if adding a very small delay before executing the shortcut fixes this?
Alternatively you could probably use the configurable screenshot action from BTT for now.

![image](https://cloud.githubusercontent.com/assets/8820811/23528509/689520f0-ff9a-11e6-894b-97e3399393e7.png)

**Comment by fifafu** [comment] 2017-03-02 21:52
Oh I just noticed the delay action doesn't work if it's the first action :-)
That I need to fix.

For now add a "no action" action as first action:
![image](https://cloud.githubusercontent.com/assets/8820811/23528639/db8f94e6-ff9a-11e6-952d-317199a2e0d7.png)

**Comment by fantaaaaaa** [comment] 2017-03-02 22:05
<img width="1127" alt="screenshot 2017-03-02 23 03 25" src="https://cloud.githubusercontent.com/assets/24585031/23529103/8d92c6da-ff9c-11e6-83d5-abacb3e8ab6d.png">

did that. problem still persists if i pick a delay shorter than this. seems like there is a real delay after i can invoke another keystroke-combination...

**Comment by fifafu** [comment] 2017-03-02 22:19
Weird, I can't seem to reproduce this.

Could you try to move the "Min pause before first keystroke" slider to the very left? In your screenshot the slider seems to be in some weird state, it's pretty far right but only shows 0,08 seconds pause.

**Comment by fantaaaaaa** [comment] 2017-03-02 23:14
yeah i think there is a bug. is the slider a general setting or is it specific to a keystroce recodring? if it is, it will not show the proper position that i set but it will stay constant through all recordings. if you are intrersted, i can investigate :)

in the meantime: yes, that fixed it! coming back to the first screenshots and the bug there :)

**Comment by fifafu** [comment] 2017-03-10 23:29
The UI bug will be fixed with the next alpha (sorry had to delay it until this weekend)

**Closed by fifafu** 2017-03-10 23:29 UTC
