### ISSUE TITLE
System default pinch gestures don't work

### ISSUE THREAD

**Issue by targumanu** [fifafu/BetterTouchTool#859] opened 2017-05-01 09:50 UTC
#### Description of bug/feature request/question:

After updating BTT to v2.094 (or maybe even an earlier version), system default pinch-in/out gestures stopped working. It happened on earlier versions as well, but usually I was able to fix it by opening the Trackpad pane in the System Preferences and toggling the "Zoom in or out" option off and back on. On 2.094, even this workaround doesn't help: The gestures are just completely ignored.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Trackpad 2

#### Device information:

Type of Mac: iMac 21.5-inch, Late 2012 (13.1)
macOS version: macOS Sierra 10.12.5 Beta (16F67a)
BetterTouchTool version: 2.094 (620)

**Comment by fifafu** [comment] 2017-05-01 13:55
Thanks for reporting! I can reproduce this, but it seems to be a bug in macOS. I'm reporting it to Apple.

It's actually the same issue as #860 , thus I'm closing that.

**Comment by fifafu** [comment] 2017-05-01 17:16
Maybe the new alpha will improve this a bit (v2.095), would be great if you could try it.

**Closed** 2017-05-06 09:19 UTC
