### ISSUE TITLE
Touchbar buttons no longer working right

### ISSUE THREAD

**Issue by CappyD** [fifafu/BetterTouchTool#2175] opened 2018-03-04 03:57 UTC
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Seems several of my touchbar buttons are no longer working correctly in recent alpha releases. All of the following worked fine about 4 alpha releases back, but have all been broken in all the recent alpha releases.

I have a Mail app touchbar defined as: Command-right arrow followed by Type Text: _(BTT)@dateformat:MM/dd/yy(BTT). When used in the File:Save As... menu in Mail, it USED to simply add an underscore and the date to the end of the mail message's title. Now, it deletes the mail message's title and leaves only the underscore and date. Note that in the File:Save As... menu, the title is highlighted/selected, but command-right arrow should not (and did not) delete it. I tried changing it to just right arrow, but same thing happens. 

Also, I have a Global button defined as cntl-shft-cmd-4 followed by Space. This USED to allow dragging out a rectangular area on the screen to copy to the clipboard. Now, it seems to ignore the Space so that it only allows copying of entire windows.

I also have buttons for the Royal TSX app (for Remote Desktop access to a Windows machine) that are defined like this: OptKeyDown, CtlKeyDown, 5, CtlKeyUp, OptKeyUP. These no longer seem to do anything on the remote machine, but I don't know how to verify if anything at all is being sent.

That's all I've seen so far, but there may well be others. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
touchbar

#### Device information:

Type of Mac: 2016 MBPro 13" with touchbar
macOS version: 10.13.3
BetterTouchTool version: 2.350

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment] 2018-03-04 08:12
Mh, are you holding a modifier key while pressing the Touchbar buttons?

**Comment by fifafu** [comment] 2018-03-04 14:37
Currenty looking at the issues.

So for the first one, I think the behavior you described is correct. BTT pastes text while there is already some text selected, thus that gets replaced. Not sure why this would ever have worked before.
However if you first send a arrow right it should work as you need it
![image](https://user-images.githubusercontent.com/8820811/36946745-fc2d3eae-1fc1-11e8-8e33-2310101c1696.png)

**Comment by fifafu** [comment] 2018-03-04 14:48
Mhh I  still can't seem to reproduce any of this. Maybe it's already fixed in my local build? Could you check whether 2.351 works for you?

**Comment by CappyD** [comment] 2018-03-04 15:35
Thanks Andreas - 2.351 fixes part of it. The first two problems I mentioned now seem to work. However, the last one is still an issue. No, I don't use a modifier key with these touchbar buttons. I can't tell if anything is being produced by the Royal TSX buttons. Is there a way that I can see exactly what BTT produces when I use one of those buttons?

**Comment by fifafu** [comment] 2018-03-04 15:43
Are you sure this worked before with Royal TSX? As far as I know there have been various reports of remote desktop software not recognizing synthetic key presses but I have never tried royal tsx.

**Comment by fifafu** [comment] 2018-03-04 15:45
Could you maybe try whether changing thw shortcut from just 5 to ctrl+opt+5 works?

**Comment by CappyD** [comment] 2018-03-04 15:49
Yes, I have used those buttons extensively for many months now and even fairly recently. Worked fine. 
So, I assume you are suggesting changing the definition from:
    OptKeyDown, CtlKeyDown, 5, CtlKeyUp, OptKeyUP
to
    OptKeyDown, CtlKeyDown, CtlOpt5, CtlKeyUp, OptKeyUP
I'll try it. 

I've been trying to think if there is an app on the Mac itself that would show exactly what keys are coming in. I could then create the same buttons to use in that app to see what is coming out of BTT.

**Comment by CappyD** [comment] 2018-03-04 15:52
same thing with that new definition

**Comment by fifafu** [comment] 2018-03-04 15:53
In System Preferences -> Keyboard -> Shortcuts you can record shortcuts that show exactly what macOS is recognizing. Unfortunately for some reason remote desktop software seems to ignore some keys for some reason...

I'd suggest to completely get rid of the opt down ctr down workaround, I believe this may not be necessary anymore.

**Comment by CappyD** [comment] 2018-03-04 16:23
When I am connected to the mainframe I use via TSX, if I press CtlOpt5 on the keyboard it works fine. A program on the mainframe looks for CrlOpt5 and does something. And the BTT touchbar button I defined as above worked the same until recently. I can't change the button definition to just 5 since the mainframe program is looking for CtlOpt5. I tried changing it to just CtlOpt5 without the preceding OptKeyDown, CtlKeyDown and following CtlKeyUp, OptKeyUP but that didn't work either.

Thanks for the sysprefs idea. I copied the TSX key in BTT to the sysprefs app in BTT and used it in sysprefs to change a shortcut key - it did not visibly change the shortcut key and I got an error sound. Of course, the sysprefs window doesn't show separate key up and down states. However, if I just define a BTT button as CtlOpt5, that works in sysprefs, but as I mentioned CtlOpt5 does not work in TSX even though directly typing CtlOpt5 does work. So, somehow that combination is not getting passed.

**Comment by fifafu** [comment] 2018-03-04 18:18
Unfortunately this issue is quite complicated to resolve because the API I previously used in BTT has been deprecated by Apple and shouldn't be used anymore. Apparently the new API doesn't allow to be used like you did.

I'm now trying a different approach by using the lowest level key event creation I know of. The key presses SHOULD look exactly like they are coming from a real keyboard, so I hope the remote desktop software won't be able to filter them out. This has some drawbacks, which is why I won't enable it by default, but you can try it in version 2.352 by enabling the compatibility mode for TSX. (See screenshot) 

![image](https://user-images.githubusercontent.com/8820811/36948821-adece586-1fe0-11e8-9321-2892d25ea9b1.png)

Would be great if you could test that in v2.352

**Comment by CappyD** [comment] 2018-03-04 18:38
tried 2.352 with the compatibility mode turned on for TSX. Unfortunately, no change. Seems that the modifiers are just not getting through like they do when typed from the keyboard.

**Comment by fifafu** [comment] 2018-03-04 18:44
Very strange. Does the "5" still come true? (In compatibility mode BTT now uses the same technique to send the modifiers and the normal key)

I think we may need to report this to the makes of these Remote Desktop softwares because this is pretty much the last supported way I know of to generate key events :-(
I have just uploaded another build of 2.352 which presses the keys for a bit longer in compatibility mode, but I don't really assume this will change anything.

**Comment by CappyD** [comment] 2018-03-04 18:59
Tried the 733 build. No change. Yes, the 5 still comes through with or without compatibility mode. I guess I can try going back to an older BTT release.

**Comment by fifafu** [comment] 2018-03-04 19:05
Yup older releases will work for now, however I assume Apple will remove the old API with one of the next bigger macOS updates...

**Comment by fifafu** [comment] 2018-03-04 19:05
One more question:
Does the TSX UI itself react to keyboard shortcuts correctly? (E.g. show/hide toolbar etc.)

**Comment by CappyD** [comment] 2018-03-04 19:16
Yep... that works fine.

**Comment by fifafu** [comment] 2018-03-04 19:17
Ok, seems like they are actively blocking synthetic events from reaching the VM then. I'll try to contact them and ask for help, maybe they have a solution or know why it doesn't work...

**Comment by CappyD** [comment] 2018-03-04 19:25
Many thanks. I actually started using Royal TSX because I had similar problems with the Microsoft Remote Desktop app not working with BTT touchbar buttons that I defined.

**Comment by fifafu** [comment] 2018-03-04 21:06
I think I might have found a workaround for Microsoft RDP and for Royal TSX => v3.353 
In my tests ist seemed to work, but let's see...

**Comment by CappyD** [comment] 2018-03-04 21:17
umm... the check for updates still says that 2.352 is the latest.

**Comment by CappyD** [comment] 2018-03-04 21:26
Hurrah... Success! It didn't work with my original key definition that did the modifiers down and then up, but works the way it really ought to as simply OptCtl5. So, even better. And that was without using compatibility mode. I haven't tried redoing all of the keys I was using, but at least two of them worked so they all should. I'll let you know if I run into any issues. But thanks so much for your determined effort!

**Comment by CappyD** [comment] 2018-03-04 22:01
Hmm, maybe a little premature. While the key, defined as OptCtl5, did its intended action (just switching workspaces), it seemed to leave the remote machine in a state just like having pressed the Option (Alt) key. I found I had to change the definition to OptCtl5, OptDown, OptUp to keep it from being in that state. Some other keys seem to fail.

**Comment by CappyD** [comment] 2018-03-04 22:06
Not sure if adding a comment gets to you after the issue is closed, so sending this via email since I don’t think I can reopen it…

Hmm, maybe a little premature. While the key, defined as OptCtl5, did its intended action (just switching workspaces), it seemed to leave the remote machine in a state just like having pressed the Option (Alt) key. I found I had to change the definition to OptCtl5, OptDown, OptUp to keep it from being in that state. Some other keys seem to fail.

Thanks,
--David



On Mar 4, 2018, at 4:43 PM, Andreas Hegenberg <notifications@github.com<mailto:notifications@github.com>> wrote:


EXTERNAL

Closed #2175<https://github.com/fifafu/BetterTouchTool/issues/2175>.

**Comment by fifafu** [comment] 2018-03-04 22:07
Don't worry the comments still arrive!
I'll check that, I think that should be easy to fix - will continue to look at it tomorrow.

**Comment by fifafu** [comment] 2018-03-05 19:02
I believe the latest alpha 2.355 should work better with the modifiers.

I'm also in contact with the dev of Royal TSX and he is very helpful.

**Comment by CappyD** [comment] 2018-03-05 19:33
Excellent to hear. I’ll be back at my machine soon and will check it out.

**Comment by CappyD** [comment] 2018-03-06 01:35
OK... I've done some testing with 2.355. It seems to work pretty well. All of my keys work most of the time. There is the occasional stumble where, again, It seems that the modifiers are not recognized. Not something I can reproduce reliably. Perhaps a timing issue?

**Comment by CappyD** [comment] 2018-03-06 14:12
It's odd because I still occasionally find that the remote machine thinks that the Option (Alt) button has been pressed. But only occasionally.

**Comment by CappyD** [comment] 2018-03-14 02:25
Just an update... I've been been using BTT with Royal TSX for a while now, and it seems to be behaving pretty well.

**Closed** 2018-03-16 16:27 UTC
