### ISSUE TITLE
"Search selected text with Google" opens new window with empty new tab

### ISSUE THREAD

**Issue by kalziqi** [fifafu/BetterTouchTool#1552] opened 2017-09-26 23:25 UTC
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

My shortcut for "Search selected text with Google" only opens a new chrome window with a blank new tab.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro Trackpad.

#### Device information:

Type of Mac: MacBook Pro, 13" Touch Bar, 2017.
macOS version: High Sierra, 10.13
BetterTouchTool version: 2.305 (683)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

https://streamable.com/2u1wu

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment] 2017-09-29 12:37
That's a bug in High Sierra. It's already fixed in 10.13.1 beta.

**Closed by fifafu** 2017-09-29 12:37 UTC

**Comment by rsiv** [comment] 2017-09-29 21:25
@fifafu, I also get a new window with empty tab on "Open URL / Open URL With Selection" action.
This started happening after I upgraded to High Sierra. 
Is it related to the same bug in High Sierra?

**Comment by SchuylerSignor** [comment] 2018-02-22 22:56
My shortcut for "Search selected text with Google" only opens a new chrome search window with a blank new tab, as above.  I'm running 10.13.3, but this just seemed to start happening.

**Comment by SchuylerSignor** [comment] 2018-02-22 23:06
Now, believe it or not, it always opens to:  "My shortcut for "Search selected text with Google" only opens a new chrome window with a blank new tab"; with 9 web results!

**Comment by Philipmad70** [comment] 2018-03-17 01:39
I had the same problem. It would sometimes search on the last searched word, and not the currently selected. And sometimes it would just open a blank page. 

But for me the issue is related to the app Popclip (that opens a toolbar when selecting text). As soon as I disable that app, the problem disapears. I dont know if that is fixable?

**Comment by cocevk** [comment] 2018-05-17 11:29
This still doesn't work for me. :-(
